### ISSUE TITLE
Rendering Glitch on OSX El Capitan

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#102]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.12
**Reported for operating system, platform:** Mac OS X 10.8, x86_64

# Comments on the original bug report:

On 2015-10-16 02:35:24 +0000, manutoo wrote:

> Hello,
> 
> as the title says, SDL_Image 1.2.12 glitches on OSX El Capitan.
> 
> I explained the problem in detail here : http://stackoverflow.com/questions/33115482/rendering-glitch-on-mac-osx-el-capitan-with-opengl .
> 
> It seems it only touches RGBA textures, but not all of them.
> 
> Using SDL_Image 1.2.10 gives a glitch-free rendering.

**Comment by slouken** [comment]
This is fixed in the next release by building with newer macOS SDK.
