### ISSUE TITLE
Library's data of dependent shared library is incorrect.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#105]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.12
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2016-04-13 13:13:53 +0000,  wrote:

> The libSDL_image.dylib building with --enable-feature-shared (e.g. --enable-png-shared) has no data of dependent shared library for specify librarys.
> It may be correct because there is no shared symbol in libSDL_image.dylib against options.
> 
> > $ otool -L libSDL_image.dylib 
> > /usr/local/lib/libSDL_image.dylib:
> >	/usr/local/opt/sdl_image/lib/libSDL_image-1.2.0.dylib (compatibility version 9.0.0, current version 9.4.0)
> >	/usr/local/opt/sdl/lib/libSDL-1.2.0.dylib (compatibility version 12.0.0, current version 12.4.0)
> >	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
> >	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
> >	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
> >	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1256.14.0)
> >	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
> >	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.6.0)
> >	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
> >	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
> 
> But the library with --enable-feature-shared=no has data against it has no shared symbol.
> The following library was built with --enable-jpg-shared=no, --enable-png-shared=no, --enable-tif-shared=no and --enable-webp-shared=no.
> 
> > $ otool -L /usr/local/Cellar/SDL_image/1.2.12/lib/libSDL_image.dylib 
> > /usr/local/Cellar/SDL_image/1.2.12/lib/libSDL_image.dylib:
> >	/usr/local/Cellar/SDL_image/1.2.12/lib/libSDL_image-1.2.0.dylib (compatibility version 9.0.0, current version 9.4.0)
> >	/usr/local/Cellar/libpng/1.6.21/lib/libpng16.16.dylib (compatibility version 38.0.0, current version 38.0.0)
> >	/usr/local/Cellar/jpeg/9b/lib/libjpeg.9.dylib (compatibility version 12.0.0, current version 12.0.0)
> >	@rpath/libtiff.5.dylib (compatibility version 5.0.0, current version 5.2.4)
> >	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
> >	/usr/local/Cellar/libwebp/0.5.0/lib/libwebp.6.dylib (compatibility version 7.0.0, current version 7.0.0)
> >	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
> >	/usr/local/Cellar/SDL/1.2.15/lib/libSDL-1.2.0.dylib (compatibility version 12.0.0, current version 12.4.0)
> >	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
> >	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
> >	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
> >	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
> >	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
> >	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.9.0)
> >	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
> >	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
> 
> It is inverse. And There is other strange point about libz.

**Comment by slouken** [comment]
This is expected, when SDL is dynamically linked against dependencies, it will open them at runtime as needed. Also, SDL_image using ImageIO does not depend on the system versions of libjpeg, libpng, etc.
