### ISSUE TITLE
Add a function to load an XPM image directly as a RGB888 surface

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#120]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [path (patch_XPM_image_RGB888.diff, text/plain, 2017-11-04 14:16:43 +0000, 2711 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3066)

**Reported in version:** unspecified
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2017-11-04 14:16:43 +0000, Sylvain wrote:

> Created attachment 3066
> path
> 
> It would be nice to have a function that loads directly an XPM image as RGB888 surface. Path already exists in SDL_image. so the patch is almost only to expose this as a function.
> (remove also MAX macro un-used).

On 2017-11-05 05:05:08 +0000, Sam Lantinga wrote:

> What's the use case for this?

On 2017-11-05 10:47:19 +0000, Sylvain wrote:

> My use case is probably marginal. 
> I have a few xpm files that I rescale linearly at run-time, so I need something else that a palette format.
> So, this function prevents a call to SDL_ConvertFormat() to converting them out of a palletized format. 
> Moreover, this way, surfaces are also immediately in the natural renderer pixel format.

**Comment by slouken** [comment]
Added in https://github.com/libsdl-org/SDL_image/commit/6157c238a77de861827fec5faaf31bf4dd51cdc4
