### ISSUE TITLE
developers should update documentation

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#128]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2018-05-01 18:03:44 +0000, N. de Jonge wrote:

> The SDL_image documentation hasn't been updated since 2009 (v1.2.8).
> 
> This is not a GUI-based end-user product, but a library for developers.
> 
> The authors of SDL_image should keep the documentation up-to-date. If an author adds, for example, IMG_SavePNG(), then that author should also document this function. Accepted parameters, expected return values, etc.
> 
> In my opinion, this is not something that (other) volunteers should do. If a function is added, removed or modified, then the documentation should be altered to reflect the changes.

**Comment by a-hurst** [comment]
Just to ping the maintainers on this (@sezero? @slouken?), I actually did a fair bit of work converting the old SDL_image documentation from the website into .rst for PySDL2 a while ago (see attached). Obviously there are some Pythonisms that would need to be removed, but would this be at all useful to you as a basis for more current documentation?

[SDL_image.rst.txt](https://github.com/libsdl-org/SDL_image/files/6542964/SDL_image.rst.txt)

Alternatively, would you be open to a PR that adds doxygen-style documentation for functions/enums/structs directly into the header, like SDL2 uses for its docs?

**Comment by slouken** [comment]
> Alternatively, would you be open to a PR that adds doxygen-style documentation for functions/enums/structs directly into the header, like SDL2 uses for its docs?

Yes, that would be great, thanks!

**Comment by a-hurst** [comment]
@slouken Great! I'll try and make some time to do this, but it might take a while to add all those docstrings so please don't hold up a new release on my account.

**Comment by slouken** [comment]
Sounds good, thanks!

**Comment by slouken** [comment]
We now have the SDL_image documentation bridged to the SDL wiki:
https://wiki.libsdl.org/SDL_image/FrontPage

Feel free to make edits on the wiki, and they will be reviewed for inclusion.
