### ISSUE TITLE
[Patch] Add USE_STBIMAGE for LoadPNG/LoadJPG, USE_TINYJPEG for SaveJPG

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#133]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[stb_image/tinyjpeg support patch (hg_patch.diff, text/plain, 2018-09-04 17:17:22 +0000, 322174 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3296)~~
* ~~[stb_image/tinyjpeg support patch [v2] (hg_patch.diff, text/plain, 2018-10-02 17:15:54 +0000, 322220 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3336)~~
* [stb_image/tinyjpeg support patch [v3] (hg_patch.diff, text/plain, 2020-01-30 21:59:22 +0000, 322500 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4183)

**Reported in version:** 2.0.3
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2018-09-04 17:17:22 +0000, Ethan Lee wrote:

> Created attachment 3296
> stb_image/tinyjpeg support patch
> 
> Attached is a patch that uses stb_image and tinyjpeg as fallbacks for configurations where libpng/libjpeg is not available. USE_STBIMAGE and USE_TINYJPEG defines are used to guard those portions of the code.
> 
> Notably absent from this patch is project file updates, including ./configure options. It shouldn't be _too_ hard to add, just '--enable-stb-image' and '--enable-tinyjpeg' with both defaulting to 'no' should be enough, and it'll only matter if libpng/libjpeg are disabled/missing.
> 
> A test repo is available here:
> 
> https://github.com/FNA-XNA/SDL_image_compact

On 2018-09-04 17:25:49 +0000, Ethan Lee wrote:

> Oh yeah, one more thing: You'll notice that IsPNG and IsJPG are duplicated for the fallback paths - I wasn't sure how to isolate that, but this could definitely be made smaller by taking the existing copies of the function and expose them to other implementations of PNG/JPG support.

On 2018-10-02 17:15:54 +0000, Ethan Lee wrote:

> Created attachment 3336
> stb_image/tinyjpeg support patch [v2]
> 
> Patch has been updated with some warning fixes for WinRT. Still need to figure out the best way to incorporate this into the projects and merge the IsPNG/IsJPG paths, need feedback on that before this can move forward.

On 2020-01-30 21:59:22 +0000, Ethan Lee wrote:

> Created attachment 4183
> stb_image/tinyjpeg support patch [v3]
> 
> New version to fix a leak in the stb loader.

**Comment by slouken** [comment]
Added in https://github.com/libsdl-org/SDL_image/commit/406fd40a7e6a9fb45ae4dfe868affdadb6d01911, thanks!
