### ISSUE TITLE
autoreconf -fi fails because "foreign" is not used

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#144]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.4
**Reported for operating system, platform:** All, x86

# Comments on the original bug report:

On 2019-02-11 12:31:52 +0000, Gabriel Kind wrote:

> I can't autoreconf SDL image because it fails with the following error:
> 
> Makefile.am: error: required file './NEWS' not found (also README AUTHORS ChangeLog)
> 
> Please either provide these 4 files in the repo or add "foreign" to AM_INIT_AUTOMAKE in configure.in

**Comment by sezero** [comment]
Fixed as of https://github.com/libsdl-org/SDL_image/commit/55ee7a81a58838849b01ddada07ae10f82e753ff
