### ISSUE TITLE
Out-of-bounds read results in information leak from the heap, in the PCX Image loader

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#164]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Example pcx file (testcrash, image/vnd.zbrush.pcx, 2020-04-07 00:52:56 +0000, 213 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4295)
* [potential patch (IMG_pcx.patch, text/plain, 2020-04-07 12:32:17 +0000, 508 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4297)

**Reported in version:** 2.0.5
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2020-04-07 00:52:56 +0000, Shubham Tandale wrote:

> Created attachment 4295
> Example pcx file
> 
> By controlling certain values in a PCX file's header, its possible to leak memory from the heap into SDL_Surface's pixels buffer. 
> 
> The bug is in the IMG_pcx.c file. "buf" is allocated with size "bpl" which is controllable from values inside the PCX header. At Ln 227, bytes are copied from the "buf" buffer into a surface's pixels buffer with a for loop depending on the WIDTH of the image which is also controllable from values in the PCX header. By setting "width" large and controlling "bpl" to be small, it is possible to leak memory past the buffer, into the surface's pixels buffer.

On 2020-04-07 12:22:55 +0000, Shubham Tandale wrote:

> To add specifics with code in IMG_pcx.c
> 
> The width for the surface is calculated via:
> 135: width = (pcxh.Xmax - pcxh.Xmin) + 1;
> 
> Here the buf is allocated with bpl bytes
> 163: bpl = pcxh.NPlanes * pcxh.BytesPerLine;
> 164: buf = (Uint8 *)SDL_calloc(bpl, 1);
> 
> Later data is copied from buf into the pixels buffer.
> 
> Uint8 *innerSrc = buf;
> int plane;
> for ( plane = 0; plane < pcxh.NPlanes; plane++ ) {
>         int x;
>         Uint8 *dst = row + plane;
>         for ( x = 0; x < width; x++ ) {
>                 if ( dst >= row+surface->pitch ) {
>                         error = "decoding out of bounds (corrupt?)";
>                         goto done;
>                 }
>                 *dst = *innerSrc++;
>                 dst += pcxh.NPlanes;
>         }
> }
> 
> There is no check to see whether "innerSrc" is past the bounds of the buffer.

On 2020-04-07 12:32:17 +0000, Shubham Tandale wrote:

> Created attachment 4297
> potential patch

**Comment by sezero** [comment]
Fixed by https://github.com/libsdl-org/SDL_image/commit/d6a758cca20f3fa451a684ae4e5152a35e752dd9

**Comment by sezero** [comment]
Reopening after https://github.com/libsdl-org/SDL_image/commit/e8eef94d83be2ca59204faccc0cac109f4e59c2a

**Comment by sezero** [comment]
I guess https://github.com/libsdl-org/SDL_image/commit/b64804ef691a8de2acfc0db107624124773f1907 fixed it again (missed that rew commit). Closing.
