### ISSUE TITLE
sdl2_image missing arch on bigsur m1

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#165]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.5
**Reported for operating system, platform:** Mac OS X (All), ARM

# Comments on the original bug report:

On 2020-12-30 15:20:33 +0000,  wrote:

> hi,
> on macos 11.2beta, macbookpro m1, 
> i installed both sdl2 and sdl2_image framework in /Library/Framework/ and on xcode it fails to compile even simple hello world, without any sdl code. when i try to build it says sdl2_image is missing required architecture. if i remove sdl2_image from linked frameworks, and leave just sdl2 instead, the hello world compiles fine.

**Comment by sezero** [comment]
I guess arm64 builds would be added to the framework in the next release.
