### ISSUE TITLE
Document optional requirements

### ISSUE THREAD

**Issue by hottwaj** [libsdl-org/SDL_image#175]
Hi it would be helpful to note the libraries/install command needed to do a basic compile on e.g. debian/ubuntu, which on ubuntu 20.04 are:

```bash
sudo apt install libwebp-dev libtiff-dev libpng-dev zlib1g-dev 
```

Either libjpeg8-dev or libjpeg9-dev is also needed, depending on the version of sdl_image you are compiling.  Unfortunately on 20.04 libtiff-dev requires libjpeg8-dev, so libjpeg9-dev can't be installed, and so sdl_image <=2.0.4 must be used rather than 2.0.5 or later.  I assume, but haven't tested, that this is fixed in e.g. 21.04

Thanks!

**Comment by sezero** [comment]
> Either libjpeg8-dev or libjpeg9-dev is also needed, depending on the version of sdl_image you are compiling.

AFAIK, SDL_image doesn't dictate a libjpeg version: it should build against libjpeg >= 6 or libjpeg-turbo

**Comment by hottwaj** [comment]
Thanks and apologies for my mistake, looks like I got confused about what was causing issues when I was installing/compiling

so for 20.04 the list is:

sudo apt install libwebp-dev libtiff-dev libpng-dev zlib1g-dev libjpeg8-dev

Shall I submit a PR to the Readme.md file with a small note documenting this?  If so I can do the same for sdl_mixer which you saw a similar comment from me on earlier today.

Thanks!

**Comment by sezero** [comment]
I don't do debian (a loyal redhat/fedora guy), but as far as I can see,
dependencies are noted in debian/control file in both SDL_image and in
SDL_mixer. Of course, if @slouken or @icculus wants it so, those can be
added to a README.

**Comment by hottwaj** [comment]
Thanks, you're right about `debian/control`.  I'm not familiar with how to package up things for debian/ubuntu, so I didn't know to look in there...

I guess compiling from source on debian/ubuntu may be fairly niche, so I totally understand if the team is happy with current setup.

Thanks!

**Comment by slouken** [comment]
The debian directory has been removed, so if you want to submit a PR that adds the info to the README, that's fine. Note that the required dependencies are actually included with the source archive.
