### ISSUE TITLE
Add sdl2_image-config.cmake to support CMake find_package()

### ISSUE THREAD

**Issue by chelmich** [libsdl-org/SDL_image#184]
As the title says, adding a `sdl2_image-config.cmake` or `SDL2_imageConfig.cmake` file would be very helpful for those building projects with this library and CMake. It would allow them to include and link the library by simply adding `find_package(SDL2_image)` to their `CMakeLists.txt`. The base SDL library as well as SDL_ttf already support this.

The current workaround is to include a third-party CMake "Find" module with your project, for example https://github.com/tcbrindle/sdl2-cmake-scripts. However, this is a somewhat ugly solution and is discouraged by the CMake developers (see https://cmake.org/Bug/view.php?id=14826).

I'm not the best with CMake, but if nobody else wants to I suppose I could take a crack at adding this myself.

**Comment by madebr** [comment]
Can you try #189?

**Comment by madebr** [comment]
#189 has been merged so this issue can be closed.
