### ISSUE TITLE
Macro Redefinition

### ISSUE THREAD

**Issue by daywithstars** [libsdl-org/SDL_image#185]
When working with cmake and including `add_subdirectory(<SDL_SOURCE_DIR>) add_subdirectory(SDL_IMAGE_SOURCE_DIR)` when compiling the SDL, SDL_image and my source code i get the error:  `SDL_image/external/jpeg-9d/./jconfig.h:56: warning: "HAVE_STDDEF_H" redefined` and `SDL/include/SDL_config_minimal.h:35: note: this is the location of the previous definition`. Maby using some macro to prevent this to be redefined, works?

**Comment by sezero** [comment]
I __hate__ that thing - that `jconfig.h` stupidity is there only to support android
builds, with no regards to use cases like this. Sigh..

As a workaround, does it help if you change the define like this:
```diff
diff --git a/external/jpeg-9d/jconfig.h b/external/jpeg-9d/jconfig.h
index 15a9817..a4a0354 100644
--- a/external/jpeg-9d/jconfig.h
+++ b/external/jpeg-9d/jconfig.h
@@ -53,11 +53,11 @@
 
 /* Define this if your system has an ANSI-conforming <stddef.h> file.
  */
-#define HAVE_STDDEF_H
+#define HAVE_STDDEF_H 1
 
 /* Define this if your system has an ANSI-conforming <stdlib.h> file.
  */
-#define HAVE_STDLIB_H
+#define HAVE_STDLIB_H 1
 
 /* Define this if your system does not have an ANSI/SysV <string.h>,
  * but does have a BSD-style <strings.h>.
```

**Comment by daywithstars** [comment]
> I **hate** that thing - that `jconfig.h` stupidity is there only to support android
> builds, with no regards to use cases like this. Sigh..
> 
> As a workaround, does it help if you change the define like this:
> 
> ```diff
> diff --git a/external/jpeg-9d/jconfig.h b/external/jpeg-9d/jconfig.h
> index 15a9817..a4a0354 100644
> --- a/external/jpeg-9d/jconfig.h
> +++ b/external/jpeg-9d/jconfig.h
> @@ -53,11 +53,11 @@
>  
>  /* Define this if your system has an ANSI-conforming <stddef.h> file.
>   */
> -#define HAVE_STDDEF_H
> +#define HAVE_STDDEF_H 1
>  
>  /* Define this if your system has an ANSI-conforming <stdlib.h> file.
>   */
> -#define HAVE_STDLIB_H
> +#define HAVE_STDLIB_H 1
>  
>  /* Define this if your system does not have an ANSI/SysV <string.h>,
>   * but does have a BSD-style <strings.h>.
> ```

This solves this warnings.
