### ISSUE TITLE
CMake: Linker error 

### ISSUE THREAD

**Issue by daywithstars** [libsdl-org/SDL_image#186]
By default sdl2 and sdl2_image compile static and dynamic using cmake, but when working on Linux x86_64 and adding sdl2 and sdl2_image source directory into my CMakeLists.txt using: add_subdirectory i get the error  when the Linker try to link the previous objects into the `libSDL2_image.so`: 

![Screenshot_2021-08-17_13-20-20](https://user-images.githubusercontent.com/42550884/129765154-856b7195-7407-435a-80e4-1f82e4f9873b.png)

The error message tells to add -fPIC(since windows works with dll, i don't know if this is an problem) onto `SDL_image/CMakelits.txt`:

![Screenshot_2021-08-17_13-42-03](https://user-images.githubusercontent.com/42550884/129766482-dcfcd55e-10f7-49cd-8be8-d00f500b6c47.png)

So, adding the code:
```
if (NOT WINDOWS)
	add_compile_options(-fPIC)
endif()
```
above `add_library(SDL2_image)` in SDL2_image/CMakeLists.txt solves this problem.
Now it works: 

![Screenshot_2021-08-17_13-50-48](https://user-images.githubusercontent.com/42550884/129767885-efc93cf4-23fb-4f7f-8689-e00e4640d9bc.png)

**Comment by daywithstars** [comment]
I have add this to a Pull request.

**Comment by madebr** [comment]
@daywithstars 
Can you try #189?
It should also address your problem.

**Comment by daywithstars** [comment]
> @daywithstars
> Can you try #189?
> It should also address your problem.

Fail with this error message:  

![Screenshot_2021-08-28_20-14-18](https://user-images.githubusercontent.com/42550884/131233275-53afe65e-a663-4c3d-be6d-cd165c9f4fee.png)

**Comment by daywithstars** [comment]
Including only the code: https://github.com/madebr/SDL_image/blob/6dab6523aa78757b893158489a1ed30597b3b37b/CMakeLists.txt#L81-L84 

Instead: https://github.com/daywithstars/SDL_image/blob/af294570ee84ec34f171ea0d1d63576435d13703/CMakeLists.txt#L22-L24 

Works end is better standard.

**Comment by madebr** [comment]
> > @daywithstars
> > Can you try #189?
> > It should also address your problem.
> 
> Fail with this error message:
> 
> ![Screenshot_2021-08-28_20-14-18](https://user-images.githubusercontent.com/42550884/131233275-53afe65e-a663-4c3d-be6d-cd165c9f4fee.png)

I don't link to `SDL2`, only `SDL2::SDL2` or `SDL2::SDL2-static`.
https://github.com/madebr/SDL_image/blob/6dab6523aa78757b893158489a1ed30597b3b37b/CMakeLists.txt#L241-L245
This is something I didn't change in my pr.
I don't know where `SDL2_image` links to `SDL2`. Perhaps you modified the cmake script somewhere?



> Including only the code: https://github.com/madebr/SDL_image/blob/6dab6523aa78757b893158489a1ed30597b3b37b/CMakeLists.txt#L81-L84
> 
> Instead: https://github.com/daywithstars/SDL_image/blob/af294570ee84ec34f171ea0d1d63576435d13703/CMakeLists.txt#L22-L24
> 
> Works, and it is better standard.

Better is relative.
Using [`CMAKE_POSITION_INDEPENDENT_CODE`](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html) is a standard compiler feature.
There's no need to add compiler specific flags to the code when cmake supports it.

**Comment by daywithstars** [comment]
> > > @daywithstars
> > > Can you try #189?
> > > It should also address your problem.
> > 
> > 
> > Fail with this error message:
> > ![Screenshot_2021-08-28_20-14-18](https://user-images.githubusercontent.com/42550884/131233275-53afe65e-a663-4c3d-be6d-cd165c9f4fee.png)
> 
> I don't link to `SDL2`, only `SDL2::SDL2` or `SDL2::SDL2-static`.
> https://github.com/madebr/SDL_image/blob/6dab6523aa78757b893158489a1ed30597b3b37b/CMakeLists.txt#L241-L245
> This is something I didn't change in my pr.
> I don't know where `SDL2_image` links to `SDL2`. Perhaps you modified the cmake script somewhere?

I just clone your cmake_work branch and add in my project instead of the official SDL_image main branch and get the error message.

**Comment by madebr** [comment]
Thanks. I didn't consider or test your use case.
I removed the call to `export` as the SDL2 main project does not do this either.
Crossing my fingers that it works now :crossed_fingers:

**Comment by daywithstars** [comment]
> Thanks. I didn't consider or test your use case.
> I removed the call to `export` as the SDL2 main project does not do this either.
> Crossing my fingers that it works now 
> 
> Thanks for the testing!

Now it works!, thanks for look to this user case.

**Comment by madebr** [comment]
#189 has been merged, so this issue can be closed.
