### ISSUE TITLE
[Feature Request] avif images support

### ISSUE THREAD

**Issue by suphamster** [libsdl-org/SDL_image#188]
<html>
<body>
<h3 id="avif_image" style="box-sizing: border-box; margin: 0px 0px 12px; font-family: zillaslab, palatino, &quot;Palatino Linotype&quot;, serif; letter-spacing: 0.035rem; line-height: 1.2; font-weight: 400; font-size: 1.953rem; color: rgb(27, 27, 27); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#avif_image" title="Permalink to AVIF&nbsp;image" style="box-sizing: border-box; color: rgb(27, 27, 27); text-decoration: none; text-decoration-skip-ink: auto;">AVIF image</a></h3><div style="box-sizing: border-box; margin-top: 1em; color: rgb(27, 27, 27); font-family: arial, x-locale-body, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: -0.0444444px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 0px 0px 24px; max-width: 85ch;">AV1 Image File Format (AVIF) is a powerful new, open source, royalty-free file format that encodes <dfn style="box-sizing: border-box;">AV1 bitstreams in the High Efficiency Image File Format (HEIF) container.</dfn></p><div class="notecard note" style="box-sizing: border-box; border-left: 6px solid rgb(0, 114, 179); margin: 0px 0px 24px; padding: 12px; background-color: rgb(221, 234, 255);"><p style="box-sizing: border-box; margin: 0px; max-width: 85ch;"><strong style="box-sizing: border-box;">Note:</strong><span> </span>AVIF has potential to become the "next big thing" for sharing images in web content. It offers state-of-the-art features and performance, without the encumbrance of complicated licensing and patent royalties that have hampered comparable alternatives.</p></div><p style="box-sizing: border-box; margin: 0px 0px 24px; max-width: 85ch;"><dfn style="box-sizing: border-box;">AV1 is a coding format that was originally designed for video transmission over the Internet. The format benefits from the signficant advances in video encoding in recent years, and may potentially benefit from the associated support for hardware rendering. However it also has disadvantages for some cases, as video and image encoding have some different requirements.</dfn></p><p style="box-sizing: border-box; margin: 0px 0px 24px; max-width: 85ch;">The format offers:</p><ul style="box-sizing: border-box; max-width: 85ch;"><li style="box-sizing: border-box; margin: 0px 0px 8px;">Excellent lossy compression compared to JPG and PNG for visually similar compression levels (e.g. lossy AVIF images are around 50% smaller than JPEG images).</li><li style="box-sizing: border-box; margin: 0px 0px 8px;">Generally AVIF has better compression than WebP — median 50% vs 30% compression for the same JPG set (source:<span> </span><a href="https://www.ctrl.blog/entry/webp-avif-comparison.html" class="external" rel=" noopener" style="box-sizing: border-box; color: rgb(0, 82, 130); text-decoration: underline; display: inline-block;">AVIF WebP Comparision</a><span> </span>(CTRL Blog)).</li><li style="box-sizing: border-box; margin: 0px 0px 8px;">Lossless compression.</li><li style="box-sizing: border-box; margin: 0px 0px 8px;">Animation/multi-image storage (similar to animated GIFs, but with much better compression)</li><li style="box-sizing: border-box; margin: 0px 0px 8px;">Alpha channel support (i.e. for transparency).</li><li style="box-sizing: border-box; margin: 0px 0px 8px;"><em style="box-sizing: border-box;">High Dynamic Range</em><span> </span>(HDR): support for storing images that can represent bigger contrasts between the lightest and darkest parts of the image. </li><li style="box-sizing: border-box; margin: 0px 0px 8px;">Wide Color Gamut: Support for images that can contain a larger range of colors.</li></ul><p style="box-sizing: border-box; margin: 0px 0px 24px; max-width: 85ch;">AVIF does not support progressive rendering, so files must be fully downloaded before they can be displayed. This often has little impact on real-world user experience because AVIF files are much smaller than the equivalent JPEG or PNG files, and hence can be downloaded and displayed much faster. For larger file size the impact can become significant, and you should consider using a format that supports progressive rendering.</p><p style="box-sizing: border-box; margin: 0px 0px 24px; max-width: 85ch;">AVIF is supported on desktop in Chrome, Opera and Firefox (behind a<span> </span><a href="https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#avif_av1_image_file_format_support" style="box-sizing: border-box; color: rgb(0, 82, 130); text-decoration: underline; text-decoration-skip-ink: auto;">preference</a>). As support is not yet comprehensive (and has no historical depth) you should provide a fallback in either<span> </span><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#jpeg" style="box-sizing: border-box; color: rgb(0, 82, 130); text-decoration: underline; text-decoration-skip-ink: auto;">JPEG</a><span> </span>or<span> </span><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#png" style="box-sizing: border-box; color: rgb(0, 82, 130); text-decoration: underline; text-decoration-skip-ink: auto;">PNG</a><span> </span>format using <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture" style="box-sizing: border-box; color: rgb(0, 82, 130); text-decoration: underline; text-decoration-skip-ink: auto;">the<span> </span><code style="box-sizing: border-box; background-color: rgb(244, 244, 244); -webkit-box-decoration-break: clone; font-family: consolas, &quot;Liberation Mono&quot;, courier, monospace; padding: 0px 3px; white-space: nowrap; overflow-wrap: break-word; text-decoration-skip-ink: none;">&lt;picture&gt;</code><span> </span>element</a> (or some other approach).</p>

MIME type | image/avif
-- | --
.avif
AV1 Image File Format (AVIF)
Chrome 85, Opera 71, and Firefox (behind a preference).Firefox 77 and later require the preference image.avif.enable set true. Firefox provides basic support for AVIF images. More advanced features are still in development — including animated images and colorspace support (bug 1682995).
2,147,483,647×2,147,483,647 pixels
Color mode support information is provided in the AV1 Bitstream & Decoding Process Specification, section 6.4.2 : Color config semantics.A non-exhaustive summary is:Color modes: YUV444, YUV422, YUV420Greyscale support: YUV400Bits: 8/10/12 bitAlpha supportICC profile supportNCLX support: sRGB, linear sRGB, linear Rec2020, PQ Rec2020, HLG Rec2020, PQ P3, HLG P3, etc.Tiling support
Lossy and lossless.
Royalty free. Licensing information is available at http://aomedia.org/license/ .

</div>
</body>
</html>

**Comment by IncubusRK** [comment]
You can pay attention to the [libheif](https://github.com/strukturag/libheif) library.
libheif support both HEIF and AVIF image formats.

**Comment by slouken** [comment]
For future reference, Chrome added AVIF support here:
https://chromium-review.googlesource.com/c/chromium/src/+/1707404

They used https://github.com/AOMediaCodec/libavif and https://github.com/videolan/dav1d for their support.
