### ISSUE TITLE
Packages on GitHub dos not match the release on libsdl.org

### ISSUE THREAD

**Issue by AJenbo** [libsdl-org/SDL_image#195]
The packages here on GitHub do not match what was uploaded to libsdl.org:

```
sdl_image-populate-prefix/src/release-2.0.5.tar.gz
    does not match expected value
      expected: 'f26f3a153360a8f09ed5220ef7b07aea'
        actual: '3446ed7ee3c700065dcb33426a9b0c6e'
```

libsdl.org is currently down and I'm trying to use GitHub for dependencies in the build system.

My guess is that there is a build process in preparing the builds and the builds simply where not uploaded to GitHub for the various tags (from the release page).

**Comment by smcv** [comment]
Tarballs made available automatically for each tag by Github are basically a `git export`. They are done by default by Github whenever a tag is pushed, and cannot be controlled or disabled by individual projects, even if the project has its own tarball releases with different content. (This is a [frequent](https://github.community/t/disable-tarball/139966) [request](https://stackoverflow.com/questions/56314075/how-to-turn-off-github-generated-and-broken-tarballs-when-i-do-a-release).)

For projects that use Autotools, the canonical source release is a `make dist` tarball, which includes some extra convenience files. That is almost certainly what was uploaded to libsdl.org.

If future releases are done using Github's "Releases" feature, then those could include their own assets identical to the ones uploaded to libsdl.org, which can come from `make dist` or whatever. These will be in addition to the tarballs made available automatically by Github (which, again, cannot be turned off or controlled: this is a feature request for the Github service itself, and cannot be resolved by individual projects).

For example, Flatpak has https://github.com/flatpak/flatpak/releases which is produced by following the Github-related parts of https://github.com/flatpak/flatpak/blob/master/doc/release-checklist.md. The `Source code (tar.gz)` is produced automatically by Github and should be ignored; the one labelled `flatpak-1.12.2.tar.xz` or similar is the correct source-code release artifact.

> The packages here on GitHub do not match

A `git export` is not guaranteed to be deterministic, even for the same git commit, so the tarballs that are made automatically by Github can never be guaranteed to remain identical over time.
