### ISSUE TITLE
[enhancement] Implement support for JPEG XL image format

### ISSUE THREAD

**Issue by DevonAA** [libsdl-org/SDL_image#204]
I'd like to use the **_much_** better image compression of the JPEG XL image format to build high resolution games.
Many Visual Novels games are created with the RenPy-engine, which uses SDL, countless games would benefit.
These games typically use hundreds or thousands of images.

Please support:
- [ ] loading JPEG XL files
- [ ] alpha/transparency

ABOUT JPEG XL:
- free, open source and royalty-free
- bitstream was frozen a year ago, December 2020 
- standard formally approved 17.December.2021 [twitter](https://twitter.com/jonsneyers/status/1471942556468584454)
- beats every other standardized format in compression and features (HDR, progressive decoding, precision, animation, channels, speed), only AVIF wins in compression for very low quality, low fidelity images
- old JPEGs can be encoded to 20% smaller JPEG XLs lossless and 100% restored to old JPEGs again
- extension is .jxl

SUPPORT:
- all mayor browser (Chrome, Firefox, Opera, Edge) already support JPEG XL, it's just not enabled yet by default
- many popular image tools already added support (check jpegxl.info / wiki links at bottom)

COMPRESSION:
- Lossy: about 60% smaller than JPEG for same visual quality
- Lossless JPEG transcoding: about 20% smaller
- Lossless: about 35% smaller than PNG (50% smaller for HDR)
(I've convert over 200.000 JPEGs into JPEG XLs in 2021 and can confirm these numbers are correct)

LINKS:
[official website](https://jpeg.org/jpegxl/index.html)
[github libjxl - JPEG XL reference implementation](https://github.com/libjxl/libjxl)
[community website](https://jpegxl.info/)
[wikipedia](https://en.wikipedia.org/wiki/JPEG_XL)
[reddit](https://www.reddit.com/r/jpegxl/) (one of the creators, Jon Sneyers, is active here)

**Comment by slouken** [comment]
You got it!

It's currently implemented for UNIX systems, building with autotools. Let me know if you need it for other platforms, and if so, how you built libjxl for that platform.

**Comment by sezero** [comment]
The library seems to have many external deps, it will be a problem if all are really needed by it.

**Comment by slouken** [comment]
> The library seems to have many external deps, it will be a problem if all are really needed by it.

It turns out only brotli and highway are necessary.

**Comment by sezero** [comment]
> > The library seems to have many external deps, it will be a problem if all are really needed by it.
> 
> It turns out only brotli and highway are necessary.

For the decoder only, I guess? If so, I hope the library allows a decoder-only build.

The issues I noted at https://github.com/libsdl-org/SDL/issues/5631#issuecomment-1120495128 are still there though. How is your Xcode build even working - did your source tree locally has the library under external/?

**Comment by slouken** [comment]
> > It turns out only brotli and highway are necessary.
> 
> For the decoder only, I guess? If so, I hope the library allows a decoder-only build.

Yes, it has a pretty clean decoder-only build, which I'm using in Xcode. I will create an Android.mk with the same set of files for reference.

> The issues I noted at [libsdl-org/SDL#5631 (comment)](https://github.com/libsdl-org/SDL/issues/5631#issuecomment-1120495128) are still there though. How is your Xcode build even working - did your source tree locally has the library under external/?

I checked in the relevant git submodule files. Try this?
`git submodule update --init --recursive`

**Comment by sezero** [comment]
> I checked in the relevant git submodule files. Try this? `git submodule update --init --recursive`

It didn't work before even with the freshly cloned repo (I sewar), but it does now... Baffled..

In any case, we need some update to `dist-hook` in our Makefile.am to eliminate cruft
from release a tarball.

**Comment by smcv** [comment]
Since libjxl seems to be rather large and not necessarily mature yet, and includes several bundled projects itself, perhaps it would make sense to exclude it from pre-prepared SDL_image releases, while leaving it available for those who are compiling from source?

I'm concerned that new releases of SDL_image, SDL_mixer and SDL_ttf have already taken several months, which is not great for ability to respond to CVEs in a timely fashion, so I'm not sure it's a great idea to keep re-scoping the next release to include more features. The new version numbering scheme should help with that, by avoiding the need to block a new bugfix release on stabilizing new features; but for that to help, we need one release with the new versioning scheme first :-)

**Comment by mrhaandi** [comment]
Chromium reactivated the abandoned jxl integration:
https://chromium-review.googlesource.com/c/chromium/src/+/7184969
based on `jxl-rs` https://github.com/libjxl/jxl-rs, which is a subproject of `libjxl`.
Now `jxl-rs` alleviates most of the concerns above, and is supposed to be lightweight, safe, and highly compatible.

Possibly, this impacts the prior decision regarding this presently closed issue.
