### ISSUE TITLE
[Bug?] IMG_SaveJPG not supported in official macOS binaries

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_image#207]
Was testing some code across platforms, and noticed that the latest official libsdl.org macOS frameworks don't seem to be built with jpeglib, meaning the `IMG_SaveJPG` and `IMG_SaveJPG_RW` functions don't work (SDL\_GetError output: `SDL_image not built with jpeglib, saving not supported`).

SDL\_Image installed via Homebrew seems to support it just fine. Any chance this is a simple fix that can be added before the next release?

Thanks in advance!

**Comment by slouken** [comment]
Added, thanks!
