### ISSUE TITLE
Error compiling libpng on arm64 via ExternalProject

### ISSUE THREAD

**Issue by SaltyQuetzals** [libsdl-org/SDL_image#214]
I've been trying to include `SDL_image` as a dependency in my project, but have been encountering difficulties due to `libpng`. I'm working on a small personal project for my own purposes, and I'm trying to ensure that other collaborators won't have to install things to their local machines before setup, as most are accustomed to a "one command and it runs" approach. I've been using CMake and the `ExternalProject` functions, but I've been encountering problems with `libpng` compiling on my system.

## OS Information
**Operating System**: MacOS Monterey
**Chip**: M1 Pro

## Compiler Information
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.4.0
Thread model: posix

## `CMakeLists.txt`

```cmake
cmake_minimum_required(VERSION 3.21)

include(ExternalProject)
include(FetchContent)
include(GNUInstallDirs)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH})
project(FOO)

ExternalProject_Add(external_freetype
        PREFIX "${CMAKE_BINARY_DIR}/external"
        URL "http://nongnu.askapache.com/freetype/freetype-2.11.1.tar.gz"
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/external/installed
        )

ExternalProject_Add(external_sdl2
        PREFIX "${CMAKE_BINARY_DIR}/external"
        GIT_REPOSITORY "https://github.com/libsdl-org/SDL"
        GIT_TAG "release-2.0.20"
        GIT_SHALLOW 1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/external/installed
        )


ExternalProject_Add(external_sdl2_ttf
        PREFIX "${CMAKE_BINARY_DIR}/external"
        DEPENDS external_sdl2 external_freetype
        GIT_REPOSITORY "https://github.com/libsdl-org/SDL_ttf"
        GIT_TAG "release-2.0.18"
        GIT_SHALLOW 1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/external/installed
        )

ExternalProject_Add(external_sdl2_image
        PREFIX "${CMAKE_BINARY_DIR}/external"
        DEPENDS external_sdl2
        GIT_REPOSITORY "https://github.com/libsdl-org/SDL_image"
        GIT_TAG "main"
        GIT_SHALLOW 1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/external/installed
        )

link_directories(${CMAKE_BINARY_DIR}/external/installed/${CMAKE_INSTALL_LIBDIR})
add_executable(${PROJECT_NAME} src/main.cpp)
add_dependencies(${PROJECT_NAME} external_sdl2)
add_dependencies(${PROJECT_NAME} external_sdl2_ttf)
add_dependencies(${PROJECT_NAME} external_sdl2_image)
add_dependencies(${PROJECT_NAME} external_freetype)
target_link_libraries(${PROJECT_NAME} PRIVATE SDL2 SDL2_ttf SDL_image freetype)
target_include_directories(${PROJECT_NAME}
        PRIVATE
        $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/src>
        $<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/external/installed/${CMAKE_INSTALL_INCLUDEDIR}>
        )
```

I'm getting a few errors:

1. `cmake-build-debug/external/src/external_sdl2_image/external/libpng-1.6.37/arm/arm_init.c` is throwing an error during compilation (`"PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"`).
2. I tried using `-DENABLE_APPLE_IMAGEIO=OFF`, that has given me the error `unknown target 'install'`.

Any suggestions? It seems like these extension libraries were designed to be installed on the user's system, but I would figure that this would fit my use case, given the CMake files in the root directory

**Comment by slouken** [comment]
SDL_image no longer depends on libpng and this change will be in the next release.
