### ISSUE TITLE
Feature: Universal DMG needed for ARM64 Macs...

### ISSUE THREAD

**Issue by jdiamondGitHub** [libsdl-org/SDL_image#215]
I realize people are still working on compiling all of the components of SDL_Image to ARM64.  I just wanted to enhance the priority on getting an M1 Mac compatible version.  Currently, this dependency is effecting all of SDL2, because the only way to use this library at the moment is to compile your entire Mac project for Intel and then run under Rosetta.  A universal framework made with modern XCode would be tremendously appreciated.  I'd be willing to help, but I need to be paired with an expert who can hold my hand through the process.

Thanks for prioritizing this.
- Jeff

**Comment by slouken** [comment]
This will be fixed in the next release.

**Comment by slouken** [comment]
The next release is now available, including ARM64 macOS support:
https://github.com/libsdl-org/SDL_image/releases/tag/release-2.6.0
