### ISSUE TITLE
SDL_image 2.0.5 mixes up surface formats

### ISSUE THREAD

**Issue by AnonN10** [libsdl-org/SDL_image#220]
I'm using SDL_image to load images in Vulkan. The issue is that when loading attached image, surface format is set to `SDL_PIXELFORMAT_ABGR8888`, but the actual layout is RGBA8888, so when trying to convert the image to `SDL_PIXELFORMAT_RGBA8888` using `SDL_ConvertSurfaceFormat`, all channels are incorrectly flipped. 24bit PNG images seem to be loaded with correct format.
Platform: Win64

[image](https://user-images.githubusercontent.com/69523725/166081536-90c60a5f-2a19-4332-bfc4-6b6c96395da7.png)

**Comment by slouken** [comment]
I'm pretty sure what's happening is that SDL's pixel formats are word-wise and Vulkan pixel formats are byte-wise, so they're actually flipped relative to each other on little-endian machines.

For example, SDL's ABGR888 format is alpha in the high bits and red in the low bits, and on little-endian machines the low bits are first and the high bits are last.

**Comment by AnonN10** [comment]
@slouken but why `SDL_PIXELFORMAT_RGB24` matches `VK_FORMAT_R8G8B8_SRGB`? What's the logic behind SDL format names?

**Comment by slouken** [comment]
The 8 bit formats are (mostly) palette indices. The 16 and 32 bit formats fit into unsigned short and unsigned int respectively, and are described by shifts and masks. The 24-bit format is an array of bytes, which is why it matches the Vulkan description, which uses byte arrays for all formats.

**Comment by AnonN10** [comment]
@slouken thanks, so I should really be using `SDL_ConvertSurfaceFormat` with `SDL_PIXELFORMAT_RGBA32`

**Comment by slouken** [comment]
I think the surface may already be in the format you want. Maybe try without any conversion? But yes, if that's not correct, you'll want to pick the SDL_PIXELFORMAT_*32 format that matches your Vulkan texture format.
