### ISSUE TITLE
Support for bit depths higher than 8bit/channel?

### ISSUE THREAD

**Issue by cesss** [libsdl-org/SDL_image#221]
The documentation doesn't say that the loaded images are forced to be 8bit/channel, but looking at the source code, it looks like all the codecs perform this conversion. Is this true, or deeper bit depths are supported in some other way?

**Comment by slouken** [comment]
SDL supports SDL_PIXELFORMAT_ARGB2101010 and similar formats for blitting, but it hasn't been optimized for them. If you're using a 3D API with SDL, then you get whatever support that 3D API has, which these days is generally very good.
