### ISSUE TITLE
Fix libjxl building using CMake

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL_image#228]
@madebr has made some upstream patches for libjxl and dependencies:
> * libjxl: apply my patch from [Wrap include directories in BUILD_INTERFACE libjxl/libjxl#1414](https://github.com/libjxl/libjxl/pull/1414) (or wait until/if upstream accepts it)
> 
> * libhighway: create a libsdl-org/libhighway fork + make sure my patch [Wrap build system include directories with generator expression google/highway#687](https://github.com/google/highway/pull/687) is included
> * brotli: create a libsdl-rog/brotli fork + apply the patch at [Wrap interface include directories with BUILD_INTERFACE generator expression google/brotli#966](https://github.com/google/brotli/pull/966) (or wait until/if upstream accepts it)

This issue is open to track the upstream pull requests. If they're not accepted, we can fork the projects and make the changes on libsdl-org repos.

**Comment by madebr** [comment]
All patches have been merged.
I think lbjxl needs extra work because it pulls in a lot of extra dependencies (such as google test).

**Comment by slouken** [comment]
I've forked brotli and highway and have updated libjxl to point to those branches, but I'm running into trouble getting them checked out in the SDL_image repo. Is there some git magic I'm missing?
```
git submodule update --init --remote --recursive               
Submodule path 'libjxl': checked out '5185eb2ec76f009cf3235f41bfce05eabfc06991'
fatal: Needed a single revision
Unable to find current origin/v1.0.9-SDL revision in submodule path 'third_party/brotli'
Failed to recurse into submodule path 'libjxl'
```

**Comment by slouken** [comment]
Okay, `git submodule update --init --remote --recursive` worked on a fresh checkout, but I had to go into the libjxl directory and do `git submodule update` on each of the upstream dependency projects.

Git gurus, feel free to explain and/or let me know what a better workflow is... @smcv?

**Comment by smcv** [comment]
Honestly, I try not to use submodules, and I don't think I've ever used nested submodules. These days I mostly use Meson, which specifically has support for "subprojects", but specifically doesn't support nested subprojects (all subprojects' recursive dependencies end up in the top-level `subprojects/` directory).

**Comment by smcv** [comment]
If you're not bundling libjxl in source code releases, and you're not including it in official binary builds either, then I have to wonder how useful it is to have it in-tree as a submodule. Would it be easier to manage as an optional external dependency? Or is dependency handling on macOS/Windows just that bad?

**Comment by slouken** [comment]
We are managing it as an optional external dependency. Because we have changes to libjxl and some of its dependencies, the repos are hosted on libsdl-org on GitHub, and we use those as submodules so we can do integrated testing.

For end users, there's a download.sh script in the external directory that can be used to download them into a freshly unpacked distribution archive.

**Comment by slouken** [comment]
But maybe the right thing to do is just to remove them as submodules and developers can also use download.sh to grab them. We'd have to adjust the CI workflows to do that, but that's probably not a problem.

**Comment by smcv** [comment]
> But maybe the right thing to do is just to remove them as submodules and developers can also use download.sh to grab them

I would personally lean towards that for libjxl, at least. The smaller dependencies like libjpeg and libpng are not so bad, but libjxl has more red flags: large, multi-layered bundled dependencies, not enabled by default.

**Comment by smcv** [comment]
In the Debian (and Steam Runtime) packaging, I'm exclusively using separately-packaged system dependencies (and in fact `external/` is completely deleted from the Debian source package, so that I have less code to audit).

I realise having all the dependencies packaged separately is a Linux distribution luxury that can't be relied on when building for Windows, macOS or embedded platforms, so I don't necessarily want to impose my Linux-distribution worldview on upstream projects - but Linux distributions tend to have "nothing is bundled" as their ideal to aim for, and I'm nearly always going to be happy with steps taken in that direction :-)

**Comment by sezero** [comment]
@slouken: If you want, I can try and butcher libjxl down to what is minimally required.

**Comment by slouken** [comment]
> @slouken: If you want, I can try and butcher libjxl down to what is minimally required.

No thanks, we'll just leave it as-is. It's removed for make-dist and people who don't do `git submodules` won't pick it up either.
