### ISSUE TITLE
CMakeLists.txt not included in `make distcheck` tarball

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL_image#233]
Is it deliberate that the `make distcheck` release tarball doesn't include `CMakeLists.txt`?

If the intention is that CMake is a "first-class citizen" (or even that it will replace Autotools eventually), then everything necessary to do a successful build with CMake should probably be in `EXTRA_DIST`.

Conversely, if the intention is that the CMake build is considered to be experimental, then it seems correct to leave it out and require CMake enthusiasts to get it from git.

**Comment by sezero** [comment]
> Is it deliberate that the `make distcheck` release tarball doesn't include `CMakeLists.txt`?

It was, yes

> If the intention is that CMake is a "first-class citizen"

Now that the works from @madebr and others are maturizing it, it can be added back
to EXTRA_DIST.

**Comment by madebr** [comment]
For SDL2_ttf, I've gone ahead and added it: https://github.com/libsdl-org/SDL_ttf/pull/213

**Comment by sezero** [comment]
> For SDL2_ttf, I've gone ahead and added it: [libsdl-org/SDL_ttf#213](https://github.com/libsdl-org/SDL_ttf/pull/213)

If you think it has matured enough, go ahead and do the same here.

**Comment by slouken** [comment]
Added in https://github.com/libsdl-org/SDL_image/commit/2c0749bf7760462cca731ce2b3c1ad2ccb0a284a
