### ISSUE TITLE
Define for SAVE_PNG support

### ISSUE THREAD

**Issue by 1bsyl** [libsdl-org/SDL_image#235]
It would be nice to re-add the define to compile out the PNG support: 

eg:

```diff
diff --git a/Android.mk b/Android.mk
index c6d83db..7e9ab1c 100644
--- a/Android.mk
+++ b/Android.mk
@@ -127,6 +136,11 @@ ifeq ($(SUPPORT_PNG),true)
     LOCAL_CFLAGS += -DLOAD_PNG
     LOCAL_STATIC_LIBRARIES += png
     LOCAL_LDLIBS += -lz
+ifeq ($(SUPPORT_SAVE_PNG),true)
+    LOCAL_CFLAGS += -DSDL_IMAGE_SAVE_PNG=1
+else
+    LOCAL_CFLAGS += -DSDL_IMAGE_SAVE_PNG=0
+endif
 endif
 
 ifeq ($(SUPPORT_WEBP),true)
diff --git a/IMG_png.c b/IMG_png.c
index 462fe2f..61b5621 100644
--- a/IMG_png.c
+++ b/IMG_png.c
@@ -23,9 +23,8 @@
 
 #include "SDL_image.h"
 
-/* We'll have PNG save support by default */
-#ifndef SAVE_PNG
-#define SAVE_PNG    1
+#if !defined(SDL_IMAGE_SAVE_PNG)
+#  define SDL_IMAGE_SAVE_PNG 1
 #endif
 
 #if defined(USE_STBIMAGE)
@@ -115,7 +116,7 @@ static struct {
     jmp_buf* (*png_set_longjmp_fn) (png_structrp, png_longjmp_ptr, size_t);
 #endif
 #endif
-#if SAVE_PNG
+#if SDL_IMAGE_SAVE_PNG
     png_structp (*png_create_write_struct) (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn);
     void (*png_destroy_write_struct) (png_structpp png_ptr_ptr, png_infopp info_ptr_ptr);
     void (*png_set_write_fn) (png_structrp png_ptr, png_voidp io_ptr, png_rw_ptr write_data_fn, png_flush_ptr output_flush_fn);
@@ -170,7 +173,7 @@ int IMG_InitPNG()
         FUNCTION_LOADER(png_set_longjmp_fn, jmp_buf* (*) (png_structrp, png_longjmp_ptr, size_t))
 #endif
 #endif
-#if SAVE_PNG
+#if SDL_IMAGE_SAVE_PNG
         FUNCTION_LOADER(png_create_write_struct, png_structp (*) (png_const_charp user_png_ver, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warn_fn))
         FUNCTION_LOADER(png_destroy_write_struct, void (*) (png_structpp png_ptr_ptr, png_infopp info_ptr_ptr))
         FUNCTION_LOADER(png_set_write_fn, void (*) (png_structrp png_ptr, png_voidp io_ptr, png_rw_ptr write_data_fn, png_flush_ptr output_flush_fn))

@@ -540,7 +599,7 @@ SDL_Surface *IMG_LoadPNG_RW(SDL_RWops *src)
 
 #endif /* LOAD_PNG */
 
-#if SAVE_PNG
+#if SDL_IMAGE_SAVE_PNG
 
 #if SDL_BYTEORDER == SDL_LIL_ENDIAN
 static const Uint32 png_format = SDL_PIXELFORMAT_ABGR8888;
@@ -732,7 +791,7 @@ static int IMG_SavePNG_RW_miniz(SDL_Surface *surface, SDL_RWops *dst, int freeds
 }
 #endif /* LOAD_PNG_DYNAMIC || !WANT_LIBPNG */
 
-#endif /* SAVE_PNG */
+#endif /* SDL_IMAGE_SAVE_PNG */
 
 int IMG_SavePNG(SDL_Surface *surface, const char *file)
 {
@@ -746,7 +805,7 @@ int IMG_SavePNG(SDL_Surface *surface, const char *file)
 
 int IMG_SavePNG_RW(SDL_Surface *surface, SDL_RWops *dst, int freedst)
 {
-#if SAVE_PNG
+#if SDL_IMAGE_SAVE_PNG
 #ifdef USE_LIBPNG
     if ((IMG_Init(IMG_INIT_PNG) & IMG_INIT_PNG) != 0) {
         if (IMG_SavePNG_RW_libpng(surface, dst, freedst) == 0) {
@@ -763,5 +822,5 @@ int IMG_SavePNG_RW(SDL_Surface *surface, SDL_RWops *dst, int freedst)
 #else
     return IMG_SetError("SDL_image built without PNG save support");
 
-#endif /* SAVE_PNG */
+#endif /* SDL_IMAGE_SAVE_PNG */
 }
```

**Comment by sezero** [comment]
If you do that, you should do an equivalent of it in autotools too.

**Comment by 1bsyl** [comment]
Ok thanks, I'll try that later!

**Comment by sezero** [comment]
Haven't looked at it, but if we do this we may do a similar thing for SAVE_JPG for consistency.

**Comment by 1bsyl** [comment]
@sezero I think this is quite ok, but not really used to updating autotools !? 
(Should all file be regenerated ? I think I have more diff )

**Comment by sezero** [comment]
I will regenerate configure shortly

**Comment by 1bsyl** [comment]
Fixed https://github.com/libsdl-org/SDL_image/commit/2f5c99c94e039c78b25490730531708112a3540d thanks !

**Comment by sezero** [comment]
This can be closed now?

**Comment by 1bsyl** [comment]
still need:
- CMake update
- Re-gen configure files

**Comment by sezero** [comment]
>     * Re-gen configure files

That I already did

**Comment by a-hurst** [comment]
@1bsyl @sezero If PNG and/or JPG save are optional, and this can be configured separately from PNG/JPEG load support, is there a method of checking whether SDL\_image has been built with/without those options? If not, is there at least an informative error message set when SavePNG/SaveJPG are called indicating that the linked version of image was compiled without those options?

**Comment by slouken** [comment]
> @1bsyl @sezero If PNG and/or JPG save are optional, and this can be configured separately from PNG/JPEG load support, is there a method of checking whether SDL_image has been built with/without those options? If not, is there at least an informative error message set when SavePNG/SaveJPG are called indicating that the linked version of image was compiled without those options?

Yes, the functions will return -1 and the error will indicate that SDL_image was built without save support. However, the default public builds will always have save support enabled. This option is only available for custom builds made by developers that want to minimize the code size and don't need save support.

**Comment by a-hurst** [comment]
> Yes, the functions will return -1 and the error will indicate that SDL_image was built without save support. However, the default public builds will always have save support enabled. This option is only available for custom builds made by developers that want to minimize the code size and don't need save support.

Ah, good to know. Thanks!
