### ISSUE TITLE
tinyjpeg encoder corrupts images with width not divisible by 8

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL_image#256]
Steps to reproduce:

* Configure with `-DSDL2IMAGE_BACKEND_STB=ON`, which uses `stb_image.h` for loading and `tiny_jpeg.h` for saving
* Configure with `-DSDL2IMAGE_SAMPLES=ON`
* Build
* `./showimage -quit -save times8.jpg test/times8.bmp -save sample.jpg test/sample.bmp`

where `times8.bmp` is this 24x40 bitmap converted to `.bmp`:

![times8](https://user-images.githubusercontent.com/1561141/169887595-62e48e67-f53e-4b99-8fd9-9dcbe0ebebda.png)

and `test/sample.bmp` is the 23x42 bitmap that I committed to this repo already.

Expected result: `times8.jpg` and `sample.jpg` look like their respective `.bmp` references, but with some quality loss.

Actual result: `times8.jpg` looks fine:

![times8](https://user-images.githubusercontent.com/1561141/169887431-063fbfc4-47e1-48ec-8326-f332400eb22b.jpg)

but `sample.jpg` has been mis-encoded:

![sample](https://user-images.githubusercontent.com/1561141/169887447-91a559f0-2f01-4cfe-aabc-35b676847a27.jpg)

Workaround: Use libjpeg, which gets this right.

**Comment by smcv** [comment]
This is one of the issues involved in #248.

The most likely reason to save JPEGs from SDL is screenshots, in which case this would probably corrupt 1366x768 screenshots, but would be fine for every other commonly-used resolution.

**Comment by sezero** [comment]
Issue doesn't seem to be reported to [mainstream](https://github.com/serge-rgb/TinyJPEG).

**Comment by smcv** [comment]
I haven't done any real investigation on this; for now, I'm only opening this issue so that I have something to refer to in a commit that works around it.

**Comment by slouken** [comment]
I can take a look at this. I'm pretty sure it's just a stride mismatch issue.

**Comment by smcv** [comment]
It could also be to do with the 8x8 encoding blocks in the JPEG format.

**Comment by slouken** [comment]
I've also filed an upstream PR: https://github.com/serge-rgb/TinyJPEG/pull/15
