### ISSUE TITLE
IMG_gif.c uses SDL_HasColorKey, which is SDL2 2.0.9+

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_image#262]
It's used here:
https://github.com/libsdl-org/SDL_image/blob/fe2c0c49cd429468870f2be0183a0294ad8fd343/IMG_gif.c#L150

Found while building SDL_image on MSVC:
https://github.com/madebr/SDL_image/runs/6582119390?check_suite_focus=true

Documentation of [SDL_HasColorKey](https://wiki.libsdl.org/SDL_HasColorKey)

Perhaps we need to bump the minimum required SDL version to 2.0.9?
If this is ok, please create a github release (including binaries) for sdl 2.0.9.

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL_image/commit/aa690a6de7e33b5456737b98abd512bb120f2f5e to bump required SDL version to 2.0.9

Keeping this open until @slouken publishes a github release for it.

**Comment by sezero** [comment]
A 2.0.9 github release is created - closing.

**Comment by madebr** [comment]
Thanks, though it has an issue:
the 2.0.9 release contains SDL2-devel-2.0.8-VC.zip, instead of SDL2-devel-2.0.9-VC.zip

https://github.com/libsdl-org/SDL/releases/tag/release-2.0.9

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by sezero** [comment]
Actually, wouldn't it be better that we use `--no-undefined` linker flag
if available?
https://github.com/libsdl-org/SDL/blob/main/configure.ac#L250
https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L608

I can copy it to all satellite projects' autotools if accepted, and @madebr
can handle cmake side.

**Comment by slouken** [comment]
Yep, that sounds good.

**Comment by sezero** [comment]
Pushed autofoo patches to SDL_mixer, SDL_image, and SDL_ttf:
https://github.com/libsdl-org/SDL_mixer/commit/8bdfdc3a88cf72151ae4639098ab30dc0ddba8ae
https://github.com/libsdl-org/SDL_ttf/commit/274ad17e98d07dc6b4ba5ddb7bcb782767832297
https://github.com/libsdl-org/SDL_image/commit/a4c08c025df3115fc8216799734cdd15b25aced8

@madebr: For cmake, here is a fair example we have been using in libxmp:
https://github.com/libxmp/libxmp/blob/master/CMakeLists.txt#L90

**Comment by madebr** [comment]
@sezero 
Thanks for the snippet!
I had something similar in mind.

https://cmake.org/cmake/help/v3.18/module/CheckLinkerFlag.html
Too bad this one needs a too recent cmake version.
