### ISSUE TITLE
test/main.c uses SDLTest_CommonLogUsage which is SDL2 2.0.10+

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_image#263]
It's used here:

https://github.com/libsdl-org/SDL_image/blob/aa690a6de7e33b5456737b98abd512bb120f2f5e/test/main.c#L1034

The function is introduced in this commit: https://github.com/libsdl-org/SDL/commit/b5d3b6fc25fc8d464938515c13937e0cb0390664
which happened between 2.0.9 and 2.0.10

The easiest solution would be to bump the minimum required sdl2 version to 2.0.10,
but this function is for the tests only.

This library [contains some usages of the `SDL_VERSION_ATLEAST` macro](https://github.com/libsdl-org/SDL_image/search?q=SDL_VERSION_ATLEAST).
But all those usages can be removed.

What do you suggest? Bump to 2.0.10 or use the `SDL_VERSION_ATLEAST` macro?

```c
#if SDL_VERSION_ATLEAST(2, 0, 10)
static const char *options[] = { "[--iterations #]", "[--execKey #]", "[--seed string]", "[--filter suite_name|test_name]", NULL };
SDLTest_CommonLogUsage(state, argv[0], options);
#else
SDLTest_CommonUsage(state);
#endif
```

I'm quite new to the project so I don't know what your policy is on this.

**Comment by sezero** [comment]
IMO, your suggestion should be fine: no need for required SDL version bump
only for the test suite.  But @slouken should decide.

**Comment by slouken** [comment]
Let's go ahead and bump the version, that's fine.

**Comment by madebr** [comment]
Older SDL2test (<2.0.20) has another issue: it uses `printf` instead of `SDL_log`.
This causes the following link error to appear:
```
SDL2test.lib(SDL_test_common.obj) : error LNK2019: unresolved external symbol __imp_printf referenced
 in function SDLTest_CommonInit [C:\Users\maarten\source\repos\SDL_image\buildmsvc\test\testimage.vcx
proj]
C:\Users\maarten\source\repos\SDL_image\buildmsvc\test\Debug\testimage.exe : fatal error LNK1120: 1 u
nresolved externals [C:\Users\maarten\source\repos\SDL_image\buildmsvc\test\testimage.vcxproj]
```
I can fix this error by linking to `legacy_stdio_definitions.lib`.
See https://docs.microsoft.com/en-us/cpp/porting/overview-of-potential-upgrade-issues-visual-cpp

Just saying that older SDL2 libraries need workarounds anyways.
With what MSVC version are the SDL2-VC sdk's built?

**Comment by slouken** [comment]
In that case let's keep the minimum SDL version at 2.0.9, and in CI download the latest SDL and use that, and just don't build the tests if the detected SDL is too old.

**Comment by slouken** [comment]
SDL is built using mingw64 to avoid depending on any specific version of the VC++ runtime.

**Comment by madebr** [comment]
> In that case let's keep the minimum SDL version at 2.0.9, and in CI download the latest SDL and use that, and just don't build the tests if the detected SDL is too old.

I've kept using 2.0.9 in #268.
I'ld like to keep using the older releases to test compatibility with older SDL releases on CI.
The workaround disables itself when the sdl version is detected to be >=2.0.20.


> SDL is built using mingw64 to avoid depending on any specific version of the VC++ runtime.

So your process is to build SDL2 + dependencies with mingw, and manually rename the static libraries to conform with MSVC?
```
mv libSDL2_image.dll.a SDL2_image.lib
```

**Comment by slouken** [comment]
No, I build the static libraries with MSVC and the DLL with mingw. Does Visual Studio recognize .a libraries now?

I had a fun moment yesterday when I built a DLL with mingw64 and debug info and was able to debug line-by-line using Visual Studio.

**Comment by madebr** [comment]
> No, I build the static libraries with MSVC and the DLL with mingw. Does Visual Studio recognize .a libraries now?

With static library, do you mean the DLL import library, using `dumpbin /EXPORTS` + postprocessing?

I think there is compatibility when using mingw import libraries. Those usually don't need a C library.
I don't know about ordinary static .a libraries.

Recently, I think a broken `FindSDL2.cmake` module caused MSVC to use the mingw SDL2 SDK.
Everything kept compiling/linking fine.
I didn't dig deeper into this afterwards.

**Comment by slouken** [comment]
> > No, I build the static libraries with MSVC and the DLL with mingw. Does Visual Studio recognize .a libraries now?
> 
> With static library, do you mean the DLL import library, using `dumpbin /EXPORTS` + postprocessing?

Yes.

> Recently, I think a broken `FindSDL2.cmake` module caused MSVC to use the mingw SDL2 SDK. Everything kept compiling/linking fine. I didn't dig deeper into this afterwards.

Interesting. Good to know!
