### ISSUE TITLE
stb_image backend and the `STBI_NEON` build time option

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_image#273]
stb_image backend doesn't enable its `STBI_NEON` build time option
by default. If we want that, we need to add it to IMG_stb.c guarded
properly.

**Comment by sezero** [comment]
Is the following correct? (Cooked blindly can't test.)
```diff
diff --git a/IMG_stb.c b/IMG_stb.c
index dc6247f..95150b4 100644
--- a/IMG_stb.c
+++ b/IMG_stb.c
@@ -46,6 +46,9 @@
 #define STB_IMAGE_STATIC
 #define STBI_NO_THREAD_LOCALS
 #define STBI_FAILURE_USERMSG
+#if defined(__ARM_NEON)
+#define STBI_NEON
+#endif
 #define STBI_NO_STDIO
 #define STBI_ONLY_PNG
 #define STBI_ONLY_JPEG
```

**Comment by 1bsyl** [comment]
Yes, in other SDL2 parts, we enable NEON compilation with 
`#if defined(__ARM_NEON)`
and there is  also a run-time check: 

`     if (SDL_HasNEON()) { ... }`

https://github.com/libsdl-org/SDL/blob/main/src/audio/SDL_audiotypecvt.c#L27
https://github.com/libsdl-org/SDL/blob/main/src/audio/SDL_audiotypecvt.c#L1413

we can patch stb_image.h easily here:
https://github.com/libsdl-org/SDL_image/blob/main/stb_image.h#L3886
right ?

**Comment by sezero** [comment]
So, it's the IMG_stb.c above change plus the one below, yes?
```diff
diff --git a/stb_image.h b/stb_image.h
index 13d51a4..c95d28f 100644
--- a/stb_image.h
+++ b/stb_image.h
@@ -3884,9 +3884,11 @@ static void stbi__setup_jpeg(stbi__jpeg *j)
 #endif
 
 #ifdef STBI_NEON
+  if (SDL_HasNEON()) { /* SDL_image change */
    j->idct_block_kernel = stbi__idct_simd;
    j->YCbCr_to_RGB_kernel = stbi__YCbCr_to_RGB_simd;
    j->resample_row_hv_2_kernel = stbi__resample_row_hv_2_simd;
+  } /**/
 #endif
 }
 
```

**Comment by 1bsyl** [comment]
yes that's seems ok to me !
