### ISSUE TITLE
Create sdl2_image-config.cmake.autotools.in

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL_image#276]
From https://github.com/libsdl-org/SDL_image/issues/182#issuecomment-1135808483:
> Another important thing to consider is only the cmake build script will install a `SDL2_imageConfig.cmake` file. Perhaps we will need to create `sdl2_image-config.cmake.autotools.in`, [similar to what SDL is doing](https://github.com/libsdl-org/SDL/blob/main/sdl2-config.cmake.in).

@madebr, if you create the template, I can wire it up to the autotools configuration for the next release.

**Comment by madebr** [comment]
Fixed in https://github.com/libsdl-org/SDL_image/commit/f257d179fa708136317a6351aa7293e3c90b95d8
