### ISSUE TITLE
2.5.2 M1 mac - Img_Load() in succession causes EXC_BAD_ADDRESS

### ISSUE THREAD

**Issue by kjblanchard** [libsdl-org/SDL_image#287]
Hello!  On the m1 mac  I'm running into issues when calling IMG_Load() multiple times in a row. The first time it always works fine, and It works fine if I add a SDL_Delay afterwards, 500 seems to do the trick.  It also works fine without the SDL_Delay on 2.5.2 on Windows (x86).  I haven't tested on Linux just yet.  As the title states, without the delay I'm getting a EXC_BAD_ADDRESS when debugging or segmentation fault on the call to IMG_Load. 

Heres a snippet of sample code I was using after debugging a bit on my end to try and locate the cause in my source.  The error is thrown from IMG_Load call when I step through too quickly.  I haven't found a workaround on the m1 mac, besides using a delay.

I first started having the issue initially when I was trying to load different images as well from a list of images, so I've tested loading different images (in the same directory) and run into the issue still.  I've also tried using .bmp files as well, and still getting the error with bmp files.  Again, only on the mac m1 on 2.5.2.

```
    auto count = 5;
    for (size_t i = 0; i < count; i++)
    {
        SDL_Surface *surf = NULL;
        SDL_Texture *tex = NULL;
        surf = IMG_Load("./assets/tiled/tilesets/purple.png");
        if (surf == NULL)
        {
            std::cout << "Error loading: " << IMG_GetError() << std::endl;
        }
        tex = SDL_CreateTextureFromSurface(renderer, surf);
        if (tex == NULL)
        {
            std::cout << "Error loading: " << IMG_GetError() << std::endl;
        }
        SDL_FreeSurface(surf);
        SDL_DestroyTexture(tex);
        SDL_Delay(500);
    }
```

**Comment by sezero** [comment]
This is possibly an alignment issue with stb_image??

I ran the following under valgrind under i686-linux, no memory errors reported.
```
$ file purple.png
purple.png: PNG image data, 1600 x 1200, 8-bit/color RGB, non-interlaced
```

```c++
#include "SDL.h"
#include "SDL_image.h"

int main (void)
{
    SDL_Renderer *renderer;
    SDL_Window *window;
    if (SDL_CreateWindowAndRenderer(800, 600, 0, &window, &renderer) < 0) {
        fprintf(stderr, "Error creating renderer: %s\n", SDL_GetError());
        return -1;
    }
    int count = 5;
    for (size_t i = 0; i < count; i++)
    {
        SDL_Surface *surf = NULL;
        SDL_Texture *tex = NULL;
        surf = IMG_Load("purple.png");
        if (surf == NULL) {
            fprintf(stderr, "Error loading: %s\n", IMG_GetError());
        }
        tex = SDL_CreateTextureFromSurface(renderer, surf);
        if (tex == NULL) {
            fprintf(stderr, "Error loading: %s\n", IMG_GetError());
        }
        SDL_FreeSurface(surf);
        SDL_DestroyTexture(tex);
//        SDL_Delay(500);
    }
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    return 0;
}
```

**Comment by kjblanchard** [comment]
As an update, I built SDL_image from source as I was trying to get a better error in my project at the latest commit and I was able to load just fine without a delay, I noticed that it was a few commits ahead so maybe it was fixed there.

On another note, to build sdl_image from source in a cpp project I needed to modify a lot of the project() calls in the cmake files throughout the SDL_image project as they explicitly state C and not CXX.   And had to change some of the required_versions for cmake as they were pretty new, I used 3.2 as that is what brew installs on macos.

Thanks for everything you guys do with SDL2!

**Comment by slouken** [comment]
> On another note, to build sdl_image from source in a cpp project I needed to modify a lot of the project() calls in the cmake files throughout the SDL_image project as they explicitly state C and not CXX; not sure if we can remove those explicit lines or just add CXX, [an example in the root CMakeLists.txt:](https://github.com/libsdl-org/SDL_image/blob/main/CMakeLists.txt#L21)
> 
> ```
> project(SDL2_image
>     LANGUAGES C
>     VERSION "${FULL_VERSION}"
> )
> ```
> 
> to
> 
> ```
> project(SDL2_image
>     LANGUAGES C CXX
>     VERSION "${FULL_VERSION}"
> )
> ```

@madebr, is this a change we want across the board?

**Comment by sezero** [comment]
I'm certainly not a cmake guy, but I can't see the need for enabling C++ in a C-only project.

**Comment by madebr** [comment]
Not really, since SDL_image is a pure C library (apart from some dependencies requiring C++).

In the original message of https://github.com/libsdl-org/SDL_image/issues/287#issuecomment-1166760485, he said he needed to these changes for CMake 3.2. But [homebrew provides CMake 3.23.2](https://formulae.brew.sh/formula/cmake).
So I don't understand the reasoning behind this need for backporting or adding CXX.

**Comment by slouken** [comment]
Okay, makes sense. Thanks!
