### ISSUE TITLE
WebP included with official Windows binaries but not macOS framework?

### ISSUE THREAD

**Issue by a-hurst** [libsdl-org/SDL_image#288]
Hi everyone,

Just testing out the new SDL2 releases with PySDL2 and noticed in the unit tests that WebP support has been removed from the official macOS release .framework. However, the changelog doesn't indicate that it was removed and the WebP .dll is still found in the "optional" folder for the Windows binaries. Was this a deliberate change or accidental?

Just wondering whether I should remove the unit test for WebP support on macOS or wait for a 2.6.1.

Also, sorry I didn't test this sooner before the official release! I've been busy with a new internship that eaten up a lot of my free time.

Best,

- Austin

**Comment by slouken** [comment]
Can you try this?
https://www.libsdl.org/tmp/SDL2_image.dmg

**Comment by sezero** [comment]
44 MB libjxl framework? Ew..

**Comment by a-hurst** [comment]
@sezero libjxl and libavif aren't bundled in the Windows binaries either (even in the "optional" folder) so I'm personally fine with leaving those bulkier formats out the Mac binaries. The key things for me are a) cross-platform parity in included codec support and b) codec support parity with the last release of image.

**Comment by slouken** [comment]
Okay, I pulled avif and jxl support from SDL_image DMG

**Comment by sezero** [comment]
AVIF: might be possible to butcher down to a decoder-only build to reduce size but it's not _that_ big to begin with.

JXL: Don't know what to do with that monstrosity..

**Comment by a-hurst** [comment]
@slouken That works perfectly, thanks! My only note is that I'd add something to the README explaining where to put the optional frameworks, I had to download the previous Image release to figure out where to put them inside the main framework.

**Comment by slouken** [comment]
The optional frameworks go in the same location as the main SDL_image.framework. If they're installed system wide, this means the /Library/Frameworks directory. If they're installed in an application bundle they should go in the Frameworks directory in the application bundle. The playwave and playmus Xcode projects show how this is done with an Xcode project.

**Comment by slouken** [comment]
I have uploaded a shippable archive of SDL_image 2.6.0 with signed optional frameworks here:
https://www.libsdl.org/tmp/SDL2_image-2.7.0.dmg

I'm not currently planning an interim release with these changes, but you can use this until the official 2.8.0 release.

**Comment by a-hurst** [comment]
Thanks a ton for this! Your efforts are very much appreciated.

**Comment by slouken** [comment]
You're welcome!

**Comment by slouken** [comment]
It's back, thanks for the heads up!
