### ISSUE TITLE
CMake CI build error

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL_image#299]
macOS CI is failing with the following error:
Run cmake --build build/ --config Release --parallel --verbose
ninja: error: '_sdl2test_library', needed by 'test/testimage', missing and no known rule to make it

**Comment by madebr** [comment]
This issue is a bug in the autotools cmake sdl2 config script, fixed in https://github.com/libsdl-org/SDL/commit/8a08d62ff701d64d7f40bcea08c01c004e2851e4

Only macos is failing because homebrew is the only package maintainer that is using the autotools build script.
The easiest solution is to disable building the test on Macos until a patch release of sdl2 happens (which the fix above is also part of).

**Comment by slouken** [comment]
Maybe we can make a development point release and depend on that for the CI?

**Comment by madebr** [comment]
I pushed 01e3cc0fae1214ec7fedabe45d0262b837973d3d already, but you made me thinking.
Homebrew supports `--HEAD`, so perhaps we can force building current development SDL2 with
```
brew install sdl2 --HEAD
```

**Comment by slouken** [comment]
Oh, that's a good idea. Let's re-enable the tests and have the SDL satellite libraries build against SDL head.

**Comment by madebr** [comment]
I pushed it in https://github.com/libsdl-org/SDL_image/commit/7378f0c2dec614af5ae5e8645391d303883d8190
Time goes from [3 minutes](https://github.com/libsdl-org/SDL_image/runs/7922968650?check_suite_focus=true) to [6 minutes](https://github.com/libsdl-org/SDL_image/runs/8195671694?check_suite_focus=true).

Are we okay with always paying this cost? Time wise (and environmental impact wise)?
Personally, I would rollback the `--HEAD` change until the sdl2 fix is used in homebrew by default.

**Comment by slouken** [comment]
> I pushed it in [7378f0c](https://github.com/libsdl-org/SDL_image/commit/7378f0c2dec614af5ae5e8645391d303883d8190) Time goes from [3 minutes](https://github.com/libsdl-org/SDL_image/runs/7922968650?check_suite_focus=true) to [6 minutes](https://github.com/libsdl-org/SDL_image/runs/8195671694?check_suite_focus=true).
> 
> Are we okay with always paying this cost? Time wise (and environmental impact wise)? Personally, I would rollback the `--HEAD` change until the sdl2 fix is used in homebrew by default.

Sure, we can roll back as long as someone is keeping an eye on when that fix goes in for homebrew.
