### ISSUE TITLE
A question regarding developer library files.

### ISSUE THREAD

**Issue by WLD-Graphic** [libsdl-org/SDL_image#301]
Hello everyone,
I'm a newbie and I have a question:-
When I checked (SDL_image library for developers) files list, I found two editions, one for VC and the other for MINGW, my question is:
Is this means the first one is to work with MS.Visual C++ and the second one is for the MinGW compiler?
And if this is true then why there isn't version 1. xxx for MinGW? (I'm talking about development in the Windows environment, not Linux)

**Comment by madebr** [comment]
> Is this means the first one is to work with MS.Visual C++ and the second one is for the MinGW compiler?

Yes this is correct.
The [MinGW SDL_image SDK](https://github.com/libsdl-org/SDL_image/releases/download/release-2.6.2/SDL2_image-devel-2.6.2-mingw.zip). is meant for developing with a MinGW toolchain.
The [VC SDL_image SDK](https://github.com/libsdl-org/SDL_image/releases/download/release-2.6.2/SDL2_image-devel-2.6.2-VC.zip) is meant for developing with VC.
Both SDK's can be used to build a Windows executable, independent on what OS you're using on your development machine.

> And if this is true then why there isn't version 1. xxx for MinGW? (I'm talking about development in the Windows environment, not Linux)

I don't understand your 2nd question. What "version 1" are you talking about?

**Comment by WLD-Graphic** [comment]
>  I don't understand your 2nd question. What "version 1" are you talking about?

The current version is **2.6.2**, I'm looking for a version that is earlier than **2.0**. I googled it and found versions like _(SDL_image-devel-1.2.12-VC.zip_) which are for **Visual Studio**.
I didn't find any version for **MinGW**.

**Comment by sezero** [comment]
See http://libsdl.org/projects/SDL_image/release/?C=M;O=A

**Comment by sezero** [comment]
Yes, there doesn't seem to be mingw-specific devel packgaes, but if it is the import lib you need then you can always generate one yourself first using gendef on the dll and then running dlltool on the generated def file.

We can close this, I guess?

**Comment by madebr** [comment]
MinGW is able to link to link to VC `.lib` libraries.
Download [SDL_image-devel-1.2.12-VC.zip](http://libsdl.org/projects/SDL_image/release/SDL_image-devel-1.2.12-VC.zip) and rename `SDL_image.lib` to `libSDL_image.a`, or pass a literal path to the `.lib` file.

e.g.
```
$ x86_64-w64-mingw32-gcc main.c SDL_image-1.2.12/lib/x64/SDL_image.lib
# or
$ ln -s SDL_image.lib SDL_image-1.2.12/lib/x64/libSDL_image.dll.a
$ x86_64-w64-mingw32-gcc a.c -LSDL_image-1.2.12/lib/x64 -lSDL_image
```

**Comment by madebr** [comment]
I'm going to close this issue as it is possible to link with VC and MinGW using the available binary sdk's.

**Comment by sezero** [comment]
For x86 yes. For x64, the result _might_ be broken _if_ my memory serves, so it'd be best to use a proper mingw-compatible import lib for it.

**Comment by madebr** [comment]
For static libraries, there will surely be problems.
But for pure import libraries that forward to a dll, what can go wrong? (just curious)

Indeed, it's probably best to use a proper import library.

**Comment by WLD-Graphic** [comment]
Thank U very much, I changed the library file name. Finally, it works.
