### ISSUE TITLE
Why stb_image as default?

### ISSUE THREAD

**Issue by illume** [libsdl-org/SDL_image#302]
Hello,

I'm trying to understand the benefits of using stb_image in SDL_image by default.
Can you please elaborate why stb_image is used now by default?

There's a number of format features it doesn't support, the speed is slower (especially compression is much worse), and it's not threadsafe for errors.

These regressions make using the libsdl . org windows binaries unsuitable for us. It will make supporting different SDL_image configurations more difficult... if different distros start compiling SDL_image with stb_image and some don't.

**Comment by slouken** [comment]
It's largely to minimize code size and external dependencies for standalone distribution.
