### ISSUE TITLE
Is there a version of SDL_Image that supports M1 Macs (ARM64)?

### ISSUE THREAD

**Issue by jdiamondGitHub** [libsdl-org/SDL_image#310]
I see some references to ARM code in the general source of SDL_IMAGE.  But when I downloaded the latest pre-build DMG (2.6.2), XCode still sees no arm64 branch.  I don't have any issues with the SDL2 library or even the SDL2_TTF library.

I was wondering if there's been an explicit build for M1 Macs yet?  Or maybe someone has experience in building from source on the M1?

Thanks so much for your help - I've been trying to rewrite my needed functions from scratch in the meantime, but getting SDL_Image to work would be so much better. :)

- Jeff

**Comment by slouken** [comment]
I'm not sure why Xcode isn't seeing arm64, I'm seeing it when I run otool on the framework:
`/Volumes/SDL2_image/SDL2_image.framework/SDL2_image (architecture arm64)`

**Comment by icculus** [comment]
@jdiamondGitHub Did this ever get resolved? We definitely have Arm64 Mac support, so I'd like to see if this just needed an updated build or something else is going wrong.  Thanks!

**Comment by Eduuxx94** [comment]
I'm trying to build sdl_image on arm64 with source and I have the same problems on my side... I tryed to use ./configure to build the lib...
