### ISSUE TITLE
request: SDL3 support

### ISSUE THREAD

**Issue by 0x4d696e68** [libsdl-org/SDL_image#319]
how about SDL3 support?

**Comment by sezero** [comment]
As if SDL3 is even ready.. It will happen when it is.

**Comment by slouken** [comment]
Once SDL3 starts stabilizing we'll branch off the SDL satellite libraries and the main code will be SDL3 compatible.

I'll leave this issue open for visibility.

**Comment by cnlohr** [comment]
Any chance this could be furthered?  The solution for SDL_ttf worked out really well if someone is willing to backport that. 

https://github.com/libsdl-org/SDL_ttf/issues/261

**Comment by cnlohr** [comment]
Correction - I mistyped my folder for CMAKE_PREFIX_PATH. Turns out that is all you need.

**Comment by sezero** [comment]
This project has been following SDL3 development for some time. This can be closed now.
