### ISSUE TITLE
Possible mislabel of SDL2_image.dll bitness in VC development archive

### ISSUE THREAD

**Issue by Verneaki** [libsdl-org/SDL_image#321]
Apologies in advance if I'm just being stupid. I found that the `SDL2_image.dll` located in `SDL2_image-devel-6.2.6-VC\lib\x64` produces an error (`"The application was unable to start correctly: 0xc000007b"`) suggesting that it is something other than a 64 bit library. I manually replaced it with the `SDL2_image.dll` contained in `SDL2_image-2.6.2-win32-x64.zip` and this appears to remedy the issue. I previously used version 6.2.1 with no issues, and [this tutorial](https://lazyfoo.net/tutorials/SDL/06_extension_libraries_and_loading_other_image_formats/windows/msvc2019/index.php) also suggests that version 6.2.1 required no such substitution.

Thank you in advance for your response.

**Comment by madebr** [comment]
They all look fine to me.

I ran the following commands:
```
$ wget --quiet https://github.com/libsdl-org/SDL_image/releases/download/release-2.6.2/SDL2_image-devel-2.6.2-VC.zip
$ unzip -q SDL2_image-devel-2.6.2-VC.zip
$ file SDL2_image-2.6.2/lib/x86/SDL2_image.dll
SDL2_image-2.6.2/lib/x86/SDL2_image.dll: PE32 executable (DLL) (GUI) Intel 80386 (stripped to external PDB), for MS Windows
$ file SDL2_image-2.6.2/lib/x64/SDL2_image.dll
SDL2_image-2.6.2/lib/x64/SDL2_image.dll: PE32+ executable (DLL) (GUI) x86-64 (stripped to external PDB), for MS Windows

$ wget --quiet https://github.com/libsdl-org/SDL_image/releases/download/release-2.6.2/SDL2_image-2.6.2-win32-x86.zip
$ unzip -q SDL2_image-2.6.2-win32-x86.zip -d x86
$ file x86/SDL2_image.dll 
x86/SDL2_image.dll: PE32 executable (DLL) (GUI) Intel 80386 (stripped to external PDB), for MS Windows

$ wget --quiet https://github.com/libsdl-org/SDL_image/releases/download/release-2.6.2/SDL2_image-2.6.2-win32-x64.zip
$ unzip -q SDL2_image-2.6.2-win32-x64.zip -d x64
$ file x64/SDL2_image.dll 
x64/SDL2_image.dll: PE32+ executable (DLL) (GUI) x86-64 (stripped to external PDB), for MS Windows

```

**Comment by slouken** [comment]
I confirmed that the SDL2_image.dll in SDL2_image-2.6.2-win32-x86.zip and SDL2_image-2.6.2-win32-x64.zip are identical to the DLLs in SDL2_image-devel-2.6.2-VC.zip. I'm not sure what happened in the original issue, but I think the files are okay.
