### ISSUE TITLE
cmake: Debug builds have a 'd' appended to the library name

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL_image#322]
Similar to https://github.com/libsdl-org/SDL/issues/6703

**Comment by madebr** [comment]
I suppose the following needs to be updated as well:
- create `libSDL3_image.so.0` instead of `libSDL3_image-3.0.so.0`
- copy so/dylib versioning behavior of SDL3 to SDL3_image
- [install `sdl3-image.pc` instead of `SDL3_image.pc`](https://github.com/libsdl-org/SDL/issues/6713)

**Comment by slouken** [comment]
Thanks, can you make similar changes for SDL_ttf and then SDL_mixer?
