### ISSUE TITLE
Visual Studio not building .dll and .lib

### ISSUE THREAD

**Issue by GeorKous** [libsdl-org/SDL_image#328]
There is an issue when i tried to build with VS2019. I had to include the SDL3/SDL_Image.h in the project properites and after i got the following errors:
1>IMG_webp.obj : error LNK2019: unresolved external symbol _WebPDecodeRGBAInto referenced in function _IMG_InitWEBP
1>IMG_webp.obj : error LNK2019: unresolved external symbol _WebPDecodeRGBInto referenced in function _IMG_InitWEBP
1>IMG_webp.obj : error LNK2019: unresolved external symbol _WebPGetFeaturesInternal referenced in function _IMG_InitWEBP
1>IMG_webp.obj : error LNK2019: unresolved external symbol _WebPDemuxInternal referenced in function _IMG_InitWEBP
1>IMG_webp.obj : error LNK2019: unresolved external symbol _WebPDemuxDelete referenced in function _IMG_InitWEBP
1>IMG_webp.obj : error LNK2019: unresolved external symbol _WebPDemuxGetI referenced in function _IMG_InitWEBP
1>IMG_webp.obj : error LNK2019: unresolved external symbol _WebPDemuxGetFrame referenced in function _IMG_InitWEBP
1>C:\Users\User\Documents\GitHub\SDL3\SDL_image\VisualC\\Win32\Debug\SDL3_image.dll : fatal error LNK1120: 7 unresolved externals

I used the SDL_image.sln from the folder named VisualC. Please tell me if i did something wrong

**Comment by madebr** [comment]
`SDL_image.vcxproj` only sets `LOAD_WEBP_DYNAMIC="libwebp-7.dll"`
https://github.com/libsdl-org/SDL_image/blob/4876d413cb0f69cb5fb1c6e98fd80ebaabaa2c54/VisualC/SDL_image.vcxproj#L111
But `IMG_webp.c` expects both `LOAD_WEBP_DYNAMIC` and `LOAC_WEBPDEMUX_DYNAMIC` defined for webp to be loaded dynamically:
https://github.com/libsdl-org/SDL_image/blob/682c823f884aef4363a8896ffb1df90cc384658a/IMG_webp.c#L58-L65

The VisualC directory is missing a pre-built  libwebpdemux.
msys2 provides `libwebp-7.dll` and `libwebpdemux-2.dll`.

**Comment by madebr** [comment]
As a stop gap, remove all `LOAD_WEBP;LOAD_WEBP_DYNAMIC="libwebp-7.dll"` from `SDL_image.vcxproj` using a text editor.
This will disable webp support.

**Comment by madebr** [comment]
@slouken Can you build libwebp again, upload both dll's, and add `LOAD_WEBPDEMUX_DYNAMIC` to the vs project?

**Comment by GeorKous** [comment]
Thank you

**Comment by madebr** [comment]
I'm reopening because the vc project is still broken.

**Comment by slouken** [comment]
This is fixed for the 2.8.0 release.
