### ISSUE TITLE
external symbol unresolved SDL_main

### ISSUE THREAD

**Issue by frostdeep** [libsdl-org/SDL_image#329]
I used the versions
SDL2-devel-2.0.22-VC and SDL2_image-devel-2.5.2-VC

and includes in my project the Includes and libs and I am getting this error.
obs: I'm trying to use it to pull image from discord using ImGui and Discord RPC SDK.

**Comment by madebr** [comment]
You need to do the following in the source where your `main` function is defined:
```c
#include "SDL.h"

int main(int argc, char *argv[]) {
    SDL_Init(SDL_INIT_EVERYTHING);
    IMG_Init(0);
    IMG_Quit(IMG_INIT_PNG);
    SDL_Quit()
    return 0;
}
```
Important is to:
- add `#include "SDL.h"` in the file containing your main function, and
- declare your main function **exactly** as `int main(int argc, char *argv[])`
