### ISSUE TITLE
SDL_image's configure script fails to detect libpng if –build argument is specified

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#33]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.10
**Reported for operating system, platform:** Mac OS X 10.6, x86

# Comments on the original bug report:

On 2011-10-27 11:08:25 +0000,  wrote:

> NOTE: This is using the latest version of SDL_image (1.2.11) from Mercurial.
> 
> The configure script for SDL_image fails to detect libpng if a –build argument is specified for i386.
> 
> Repro Steps:
> 
> - get libpng-1.5.5.tar.gz from http://www.libpng.org/pub/png/libpng.html
> 
> - compile libpng from i386
> 
> 	open console window and cd to libpng source folder
> 	./configure –build=i386-apple-darwin10.8.0
> 	make CFLAGS="-arch i386" LDFLAGS="-arch i386"
> 	make install
> 	lipo –info /usr/local/lib/libpng.dylib
> 	Non-fat file: /usr/local/lib/libpng.dylib is architecture: i386
> 
> - then, configure SDL_image
> 
> 	cd _SDL_image_1.2.11
> 	./configure –build=i386-apple-darwin10 –disable-sdltest
> 
> > BUG: 
> 
> 	configure: WARNING: *** Unable to find PNG library (http://www.libpng.org/pub/png/libpng.html)
> 	configure: WARNING: PNG image loading disabled
> 
> However, if you compile libpng without the –build argument (i.e. building for x86_64) :
> 
> 	./configure
> 	make
> 	make install
> 
> And then invoke SDL_image's configure script without the –build argument, then the libpng library is found:
> 
> 	./configure –disable-sdltest
> 
> The work-around is to invoke SDL_image's configure script *with* the i386 build argument, and then modify the Makefile to add the missing info to the DEFS entry:
> 
> 	-DLOAD_PNG=1
> 	-DLOAD_PNG_DYNAMIC="\libpng.dylib\"
> 
> I hope this helps!
> 
> Regards,
> Alain

On 2013-06-03 01:35:34 +0000, Sam Lantinga wrote:

> This is probably a general problem with all dependency library detection.  Please let me know if you find a fix!

**Comment by sezero** [comment]
This SDL-1.2 branch issue won't be fixed.
