### ISSUE TITLE
cmake using SDL2_Image via FetchContent

### ISSUE THREAD

**Issue by juan-medina** [libsdl-org/SDL_image#338]
Hi, I opened this originally as a [stackoverflow question](https://stackoverflow.com/questions/75551185/cmake-using-sdl2-and-sdl2-image-via-fetchcontent), but unfortunately it did not get any answer.

I've a small **cmake** project that uses SDL via **FetchContent**, this work well with just SDL. I try to use the same approach to include SDL_Image, however I can not get it to work.

```cmake
cmake_minimum_required(VERSION 3.24)
project(sdl_test)

set(CMAKE_CXX_STANDARD 20)

include(FetchContent)
Set(FETCHCONTENT_QUIET FALSE)

FetchContent_Declare(
        SDL2
        GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
        GIT_TAG release-2.26.3
        GIT_SHALLOW TRUE
        GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(SDL2)

FetchContent_Declare(
        SDL2_image
        GIT_REPOSITORY https://github.com/libsdl-org/SDL_image.git
        GIT_TAG release-2.6.3
        GIT_SHALLOW TRUE
        GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(SDL2_image)

add_executable(sdl_test main.cpp)
target_link_libraries(sdl_test SDL2::SDL2main SDL2::SDL2-static SDL2_image::SDL2_image-static)
```

This produce the following error

```txt
CMake Error: install(EXPORT "SDL2ImageExports" ...) includes target "SDL2_image" which requires target "SDL2" that is not in any export set.
CMake Error at CMakeLists.txt:28 (target_link_libraries):
  Target "sdl_test" links to:

    SDL2_image::SDL2_image-static

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

Is there anything that I can do to make it work? 

I understand that there is other options, such installing the libraries on the OS, but I was trying to use **FetchContent**.

Thanks for any response!

**Comment by madebr** [comment]
The CMake script of SDL2_image builds only a shared or static library, not both.
So you need to set `BUILD_SHARED_LIBS` to a false-ish value.

Also, you need to disable the installation targets of SDL2_image (this has been fixed in git).

So your cmake script should become:
```cmake
cmake_minimum_required(VERSION 3.24)
project(sdl_test)

set(CMAKE_CXX_STANDARD 20)

include(FetchContent)
Set(FETCHCONTENT_QUIET FALSE)

FetchContent_Declare(
        SDL2
        GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
        GIT_TAG release-2.26.3
        GIT_SHALLOW TRUE
        GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(SDL2)

FetchContent_Declare(
        SDL2_image
        GIT_REPOSITORY https://github.com/libsdl-org/SDL_image.git
        GIT_TAG release-2.6.3
        GIT_SHALLOW TRUE
        GIT_PROGRESS TRUE
)

# START ADDITION
set(SDL2IMAGE_INSTALL OFF)
set(BUILD_SHARED_LIBS FALSE)
# END ADDITION

FetchContent_MakeAvailable(SDL2_image)

add_executable(sdl_test main.cpp)
target_link_libraries(sdl_test SDL2::SDL2main SDL2::SDL2-static SDL2_image::SDL2_image-static)
```

**Comment by juan-medina** [comment]
Many thanks, this works perfectly now, if you like to answer the question in the [stakoverflow question](https://stackoverflow.com/questions/75551185/cmake-using-sdl2-and-sdl2-image-via-fetchcontent) I can, very gladly, mark it as accepted answer.

If not let me know, so I'll answer myself to get it there as well resolved, just in case other people try to do the same thing and so they don't need to create issues here!

Either way, very good work

**Comment by madebr** [comment]
I'll leave the StackOverflow thing to you.
Please mention this is the SDL2 behavior.

SDL2 is able to create a shared and static library, configurable through `SDL2_SHARED` and `SDL2_STATIC`.
Both are enabled by default.
SDL2_image is only able to configure one at a time (using `BUILD_SHARED_LIBS`).

SDL3's default has changed: `SDL3_SHARED` and `SDL3_STATIC` are initialized by `BUILD_SHARED_LIBS` (during first configuration).
If `BUILD_SHARED_LIBS` is not defined, then only `SDL3_SHARED` is enabled.
If `BUILD_SHARED_LIBS` is defined, it can build tdecides what one).
Either ways `SDL3_SHARED` and `SDL3_STATIC` remain the ultimate options.

It isn't implemented yet, but SDL3_image will probably follow the same behavior as SDL3 and be able to build both shared and static configurations.

**Comment by juan-medina** [comment]
Done, thanks again @madebr

**Comment by madebr** [comment]
No problem.
I edited my message above, because the SDL options `SDL_SHARED` and `SDL_STATIC` do not contain a version number.

**Comment by juan-medina** [comment]
update there as well!
