### ISSUE TITLE
SDL3 satellite libraries need symbol versioning

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_image#339]
Since SDL3, SDL uses symbol versioning on platforms that support it.
See https://github.com/libsdl-org/SDL/issues/2786

SDL_image, SDL_mixer and SDL_ttf might also need this.

**Comment by slouken** [comment]
Yup, I agree. Does someone want to add this?

**Comment by madebr** [comment]
I will add this while I am upgrading the CMake scripts.

**Comment by smcv** [comment]
The SDL3 branches of _image, _mixer and _ttf now have this. Are there any more satellite libraries being ported to SDL3, or can this issue be closed?

**Comment by madebr** [comment]
SDL_net does not have it. But I don't know whether that library will see the light of SDL3.

**Comment by slouken** [comment]
We're all good, thanks!

**Comment by sezero** [comment]
>  Are there any more satellite libraries being ported to SDL3, 

There is SDL_rtf, but there seems to be no interest in it.
