### ISSUE TITLE
Compiling with Clang on Windows fails at version.rc

### ISSUE THREAD

**Issue by AlpRabbit** [libsdl-org/SDL_image#347]
I tryed to compile on WIndows 10 with clang, cmake and ninja. These are the versions I used.
```cmd
> cmake --version
cmake version 3.26.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).

> ninja --version
1.11.0

> clang --version
clang version 15.0.7
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

When I try to compile, it stops with the following error.
```cmd
[7/23] Building RC object _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/version.rc.res
FAILED: _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/version.rc.res
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_llvm_rc C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2_ttf-src/version.rc _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/version.rc.res.pp C:\PROGRA~1\LLVM\bin\clang.exe -DBUILD_SDL -DDLL_EXPORT -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MICRO_VERSION=2 -DSDL_BUILD_MINOR_VERSION=20 -DRC_INVOKED -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2_ttf-src -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2-build/include -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2-build/include-config-debug -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2_ttf-build/external/freetype/include -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2_ttf-src/external/freetype/include  -MD -MF _deps\sdl2_ttf-build\CMakeFiles\SDL2_ttf.dir\version.rc.res.d -x c -E -- C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2_ttf-src/version.rc ++ C:\PROGRA~1\LLVM\bin\llvm-rc.exe -DBUILD_SDL -DDLL_EXPORT -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MICRO_VERSION=2 -DSDL_BUILD_MINOR_VERSION=20 -I SOURCE_DIR -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2_ttf-src -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2-build/include -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2-build/include-config-debug -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2_ttf-build/external/freetype/include -I C:/Users/%USERNAME%/Projects/dmk/build/_deps/sdl2_ttf-src/external/freetype/include  -MD -MF _deps\sdl2_ttf-build\CMakeFiles\SDL2_ttf.dir\version.rc.res.d /fo _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/version.rc.res _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/version.rc.res.pp
llvm-rc: Error in VERSIONINFO statement (ID 1):
Non-ASCII 8-bit codepoint (・ｽ) can't be interpreted in the current codepage
```
NOTE : I chaged my user name to `%USERNAME%`

It seems like using `©` in version.rc is causing the problem. Could you change it to something like `(C)` or something else?

NOTE : This also happens with SDL_ttf, SDL_mixer and SDL_net for same reason.

**Comment by madebr** [comment]
[The main SDL project does `Copyright (C)` as well](https://github.com/libsdl-org/SDL/blob/586004e52a7bb81ab970e58804620dec4e3b1d70/src/core/windows/version.rc#L28), so this change would be accepted immediately.

**Comment by 1bsyl** [comment]
updated libs thanks !

https://github.com/libsdl-org/sdl2-compat/commit/5c8c72c4468b902216d4e611c5398374224e04c3
https://github.com/libsdl-org/SDL_ttf/commit/97c00b58166369d717ad3721d05d88cd17c9f08c
https://github.com/libsdl-org/SDL_mixer/commit/cca82a2e6da29a534a7e769e511a606671ce6269
https://github.com/libsdl-org/SDL_image/commit/0bd8290b776baf719d9fc7969b39b0a2876bb41b

**Comment by AlpRabbit** [comment]
It worked. Thank you very much.

**Comment by 1bsyl** [comment]
thanks for the feedback!

**Comment by 1bsyl** [comment]
And for SDL2 : 
https://github.com/libsdl-org/SDL_mixer/commit/0fccfe9694fc934cc7b90f71847352cc8f479d7f
https://github.com/libsdl-org/SDL_ttf/commit/9c9dbf3ed9a2073d127c6fa99e914cefa39fa1ec
https://github.com/libsdl-org/SDL_image/commit/9811cb501b861cb3110c203bae0d6b89ada7c0f9
(cc@sezero )

**Comment by 1bsyl** [comment]
12compat
https://github.com/libsdl-org/sdl12-compat/commit/10fa8dd64d97af3ff9fa46e50197586f7383db1e

net
https://github.com/libsdl-org/SDL_net/commit/3b1a3afed36e57dba1d35cf2fb47ce66d4abd922
net 12:
https://github.com/libsdl-org/SDL_net/commit/3b1a3afed36e57dba1d35cf2fb47ce66d4abd922

rtf:
net/commit/70b04a3087b4329d75affb766b4c84a977a546c0
rtf 12:
net/commit/70b04a3087b4329d75affb766b4c84a977a546c0
