### ISSUE TITLE
Is it possible to release a new version of SDL1.2 that contains patches since 1.2.12?

### ISSUE THREAD

**Issue by A1ca7raz** [libsdl-org/SDL_image#357]
Is it possible to release a new version of SDL1.x that contains commits since 1.2.12?

**Comment by icculus** [comment]
I think this falls into the same policy as SDL 1.2 itself: we aren't doing any more formal releases for this branch (and in SDL_image's case, we haven't for over 11 years).

**Comment by madebr** [comment]
You will need to download archives of the SDL-1.2 branch instead of from a tagged release.
https://docs.github.com/en/repositories/working-with-files/using-files/downloading-source-code-archives#downloading-source-code-archives
https://github.com/libsdl-org/SDL_image/archive/refs/heads/SDL-1.2.zip
