### ISSUE TITLE
SDL_HasColorKey entry point can't be found in DLL in SDL_Image 2.6.3 and SDL2 version 2.26.4

### ISSUE THREAD

**Issue by masondb** [libsdl-org/SDL_image#359]
When I run the file in my program, it gives the error:

```
The procedure entry point SDL_HasColorKey could not be located in the dynamic link library:

then shows the correct path to the SDL2_image.dll file
```

I am using VS 2022 Community Edition with Windows 10.
I tried the files on the release in the zip files, same issue. I tried 2.6.2 and I had the same issue.
I used CMake then rebuilt everything and I have the same issue. 

I am including the right header and linking the right lib file in my project.

I'm sure what is causing this.

**Comment by madebr** [comment]
Make sure you have a recent `SDL2.dll` and `SDL2_image.dll` copied in the same location as your application executable.
If that fixes it, there may be a stray `SDL2.dll` lingering in your Windows system directories (e.g. `C:\Windows`, `C:\Windows\system32`, ...)

**Comment by masondb** [comment]
I looked at that too but I did find a stray SDL2.dll outside the directory and that seemed to fix it!

Thanks!
