### ISSUE TITLE
SVG - feGaussianBlur not supported

### ISSUE THREAD

**Issue by DeaeLunae** [libsdl-org/SDL_image#361]
feGaussianBlur does not appear to be supported as of [c37c316]. Parameter seems to be skipped, but I can't tell for certain.

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feGaussianBlur

**Comment by DeaeLunae** [comment]
Sample SVG:

![test234](https://user-images.githubusercontent.com/80430868/235933698-a4a208e5-84de-4bc7-b8a0-6947bd8ee5d7.svg)

SDL output:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/80430868/235933865-1d101a12-b8c0-4743-ba1d-7c8e9262b18d.png">

**Comment by slouken** [comment]
That's correct, SDL_image supports the SVG features provided by https://github.com/memononen/nanosvg.

However, feel free to submit a PR adding functionality!
