### ISSUE TITLE
Why is there no initialization for 'IMG_INIT_GIF'?

### ISSUE THREAD

**Issue by JesseZ332623** [libsdl-org/SDL_image#376]
![image](https://github.com/libsdl-org/SDL_image/assets/101250851/fe8b8297-ef50-4c4d-820b-31537c29b5e8)
Does SDL2 not support GIF files?

**Comment by smcv** [comment]
Formats that are built-in to the library (including GIF and SVG) don't need initialization: either they're compiled in or they aren't.
