### ISSUE TITLE
Linux so version incorrect

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL_image#385]
When building on Linux, the output library is libSDL3_image.so.0.0.0 instead of 3.0.0. This happens for SDL_mixer and SDL_ttf as well, so the fix should be applied across all the satellite libraries.

I'm sure this affects Debian experimental, so this should be fixed ASAP.

Thanks!

**Comment by madebr** [comment]
SDL3 also creates `libSDL3.so.0.0.0`.
My understanding was the extension is: `$SOVERSION_MAJOR.$SOVERSION_MINOR.$SOVERSION_PATCH`.

So for SDL3, cmake creates:
```
libSDL3.so -> libSDL3.so.0
libSDL3.so.0 -> libSDL3.so.0.0.0
libSDL3.so.0.0.0
```

**Comment by slouken** [comment]
You're right, I forgot that we reset the major version to zero for SDL3.
