### ISSUE TITLE
Should wiki be split into SDL3_image and SDL2_image?

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL_image#387]
(Please don't make changes to revision control to close this bug, I need to correct this on the wiki server first if we're splitting this up.)

We have separate wiki subdirs for SDL2_mixer and SDL3_mixer, but it looks like we only have SDL2_image right now. Has the API not changed at all, or should I split this into an SDL3 wiki subdir for the main branch?

**Comment by slouken** [comment]
The API hasn't changed, but let's go ahead and split the wiki for the satellite projects.

**Comment by icculus** [comment]
This is done.
