### ISSUE TITLE
testimage svg failures after commit 9f5859e

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_image#396]
Commit 9f5859e merged rounding changes from mainstream: [memononen/nanosvg@b30716c](https://github.com/memononen/nanosvg/commit/b30716cb9caa0e63eeddfddd1d782b4a058c0713) and its follow-up [memononen/nanosvg@cb0ae54](https://github.com/memononen/nanosvg/commit/cb0ae54e6b147ccdf85401ef3ef20f2c761252c0) ([memononen/nanosvg#247](https://github.com/memononen/nanosvg/pull/247))

That resulted in testimage failures. The output files zipped + attached: [outfiles-bmp.zip](https://github.com/libsdl-org/SDL_image/files/13165292/outfiles-bmp.zip)

The results seems visually same to me, but please have a look and advise
(github doesn't seem to allow bmp attachments, therefore they are converted
to png with 0-compression using gimp.) These results are from a run on an
i686-linux setup.

CC: @smcv, @slouken 

```
ERROR: 10/25/23 13:59:33: Comparison of pixels with allowable error of 0 failed 125 times.
ERROR: 10/25/23 13:59:33: First detected occurrence at position 30,4 with a squared RGB-difference of 3.
ERROR: 10/25/23 13:59:33: Surfaces from failed comparison saved as 'CompareSurfaces0050_TestOutput.bmp' and 'CompareSurfaces0050_Reference.bmp'
ERROR: 10/25/23 13:59:33: Assert 'Surface differed from reference by at most 0 in 125 pixels': Failed
INFO: /tmp/SDL_image/test/svg-class.svg:
[...]
```
![CompareSurfaces0050_Reference](https://github.com/libsdl-org/SDL_image/assets/4222725/930dfe70-df1d-47aa-8339-61331d5006e9)
![CompareSurfaces0050_TestOutput](https://github.com/libsdl-org/SDL_image/assets/4222725/c145a62c-03fc-4b81-ad2e-360b16aa9782)

```
ERROR: 10/25/23 13:59:33: Comparison of pixels with allowable error of 0 failed 125 times.
ERROR: 10/25/23 13:59:33: First detected occurrence at position 30,4 with a squared RGB-difference of 3.
ERROR: 10/25/23 13:59:33: Surfaces from failed comparison saved as 'CompareSurfaces0051_TestOutput.bmp' and 'CompareSurfaces0051_Reference.bmp'
ERROR: 10/25/23 13:59:33: Assert 'Surface differed from reference by at most 0 in 125 pixels': Failed
INFO: /tmp/SDL_image/test/svg-class.svg:
[...]
```
![CompareSurfaces0051_Reference](https://github.com/libsdl-org/SDL_image/assets/4222725/1e238596-310c-4e76-923c-39cb27fbf7bb)
![CompareSurfaces0051_TestOutput](https://github.com/libsdl-org/SDL_image/assets/4222725/09e4427a-d975-4cc5-97cd-d3a16fc3d7ff)

```
ERROR: 10/25/23 13:59:33: Comparison of pixels with allowable error of 0 failed 125 times.
ERROR: 10/25/23 13:59:33: First detected occurrence at position 30,4 with a squared RGB-difference of 3.
ERROR: 10/25/23 13:59:33: Surfaces from failed comparison saved as 'CompareSurfaces0052_TestOutput.bmp' and 'CompareSurfaces0052_Reference.bmp'
ERROR: 10/25/23 13:59:33: Assert 'Surface differed from reference by at most 0 in 125 pixels': Failed
INFO: /tmp/SDL_image/test/svg-class.svg:
[...]
```
![CompareSurfaces0052_Reference](https://github.com/libsdl-org/SDL_image/assets/4222725/69abe248-7450-472f-bdc6-afdec0775d3d)
![CompareSurfaces0052_TestOutput](https://github.com/libsdl-org/SDL_image/assets/4222725/1b6d09d4-b863-41d3-974e-d6c137e36745)

```
ERROR: 10/25/23 13:59:33: Comparison of pixels with allowable error of 0 failed 125 times.
ERROR: 10/25/23 13:59:33: First detected occurrence at position 30,4 with a squared RGB-difference of 3.
ERROR: 10/25/23 13:59:33: Surfaces from failed comparison saved as 'CompareSurfaces0053_TestOutput.bmp' and 'CompareSurfaces0053_Reference.bmp'
ERROR: 10/25/23 13:59:33: Assert 'Surface differed from reference by at most 0 in 125 pixels': Failed
INFO: /tmp/SDL_image/test/svg-class.svg:
[...]
```
![CompareSurfaces0053_Reference](https://github.com/libsdl-org/SDL_image/assets/4222725/579e4f72-af8b-4547-866d-e0b9adf1adde)
![CompareSurfaces0053_TestOutput](https://github.com/libsdl-org/SDL_image/assets/4222725/a0540a18-43d0-4c2f-91cb-d28973632ec3)

**Comment by smcv** [comment]
I think that's close enough, and it would make sense to consider this to be an intentional nanosvg change and update the expected bmps to match the real output.

**Comment by slouken** [comment]
> I think that's close enough, and it would make sense to consider this to be an intentional nanosvg change and update the expected bmps to match the real output.

Agreed.

**Comment by sezero** [comment]
Updated reference svg-class.bmp in both SDL2 and SDL3 branches.
