### ISSUE TITLE
upgrade vendored libtiff to 4.6.0 for SDL3_image

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL_image#397]
This will make us track latest libtiff with all bug fixes already in. I created a [v4.6.0-SDL branch](https://github.com/libsdl-org/libtiff/tree/v4.6.0-SDL) with two commits cherry-picked from master.

CC: @madebr: Can you prepare the rest, e.g. cmake'ry and such?

**Comment by madebr** [comment]
I pushed 2 little patches to make integration in SDL_image as frictionless as possible.

btw, https://github.com/libsdl-org/libtiff/commit/0a44dcebf32e871320f7630ea848876774043ef8 is not really needed for SDL_image's purpose.
It's only useful when you install a complete libtiff sdk, including headers and libraries. SDL_image does not install any tiff headers and/or win32 tiff import libraries.

**Comment by sezero** [comment]
OK, it's ready then?

**Comment by sezero** [comment]
P.S.: @slouken: Android.mk doesn't even mention tiff: We don't want to support tiff in android builds, or is it an oversight?

**Comment by madebr** [comment]
> OK, it's ready then?

I tried building with my native toolchain + mingw, and it works. So you have a go from me :)
