### ISSUE TITLE
PNG Transparency stopped working with v2.8.0 without setting the color key

### ISSUE THREAD

**Issue by dstarosta** [libsdl-org/SDL_image#402]
The "image" variable is an SDL_Surface containing a PNG image with transparent pixels. Previously, the following code would work correctly.

`SDL_BlitSurface(image, NULL, current_target_surface, &rect);`

Now transparent pixels are rendered as black pixels unless I set the color key before the "SDL_BlitSurface" call as follows:

`SDL_SetColorKey(image, SDL_TRUE, SDL_MapRGBA(image->format, 0, 0, 0, 0));
`

**Comment by slouken** [comment]
Did you mean to close this? If so, what was the issue? Was it that your PNG files had a palette?

**Comment by dstarosta** [comment]
It was an indexed PNG file.

**Comment by slouken** [comment]
Was the PNG tagged as transparent? If so, can you please attach a sample image and reopen this bug? We should be setting the color key internally if the image is transparent.

**Comment by dstarosta** [comment]
I attached a couple of files that we be drawn with transparency without setting the color key in the older versions of the library.

[graphics.zip](https://github.com/libsdl-org/SDL_image/files/13625509/graphics.zip)

**Comment by slouken** [comment]
Fixed, thanks!

**Comment by slouken** [comment]
Actually, I tested the case where the surface is converted to a texture. Blitting should also work, but can you verify that?
