### ISSUE TITLE
Problems with non-ASCII chars in image paths in Windows 7

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#44]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.12
**Reported for operating system, platform:** Windows 7, x86

# Comments on the original bug report:

On 2012-04-27 14:18:14 +0000, Pere wrote:

> Hi, at Tux Paint there is this bug report [1], a quick test with fopen(fname, "r")) goes right, so the images are accesible at the path described by fname.
> 
> An additional test is -with the file manager inside W7- to drag a image over showimage.exe, the results are that the image only displays if the chars of the path to the image are all ASCII.
> 
> [1] http://sourceforge.net/tracker/?func=detail&aid=3473049&group_id=66938&atid=516295

On 2012-05-24 13:54:03 +0000, Pere wrote:

> Well, I followed the trace of the filaname passed to IMG_Load() up to the win32_file_open() function in the SDL-1.2.15/src/file/SDL_rwops.c file, it is unchanged untill arriving there, then it is recoded in this function, thus changing the path and avoiding to load the file.
> 
> If in win32_file_open() I force the use of filename as it is passed to the function ( h = CreateFile(filename, (w_right|r_right).....) instead of the recoded filenameW (h = CreateFileW(filenameW, (w_right|r_right), .....), then it loads right the images with non ascii chars on their path.
> 
> I don't provide a patch as I don't know enouth the code to understand what side effects this change can have.
> 
> Hope this helps
> Pere

**Comment by sezero** [comment]
This requires changes to SDL-1.2 RWops for windows, which won't happen.  Closing.
