### ISSUE TITLE
libwebp DLLs aren't detected by CMake's `$<TARGET_RUNTIME_DLLS:...>` with FetchContent

### ISSUE THREAD

**Issue by sam20908** [libsdl-org/SDL_image#456]
When I link my project with SDL3_image and copy the DLLs using CMake's example code at https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_RUNTIME_DLLS, only `SDL3_image.dll` is copied.

`webp` is enabled BTW.

Tested on latest commit from here as of this time's writing

**Comment by madebr** [comment]
By default, SDL_Image and SDL_mixer load the 3rd party libraries using win32's `LoadLibrary`.
So CMake is not aware of the dependency.
Configure CMake with `-DSDL3IMAGE_DEPS_SHARED=OFF --fresh` to link against these libraries instead.

**Comment by sam20908** [comment]
I see.
