### ISSUE TITLE
SDL_image + libpng load some PNGs incorrectly

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_image#460]
Hello, I'm one of the maintainers of pygame-ce. One of our users reported a png file loading incorrectly in their program.

The image:
![2_img_broken](https://github.com/user-attachments/assets/b34d6709-cb47-48b6-bfe5-721fee95a885)

![image](https://github.com/user-attachments/assets/ffdcbaaf-e633-4862-b6c1-c8932bb1d380)
It should look like the left, but instead loads as the right.

This only seems to be an issue when SDL_image is built with libpng (as we do for distribution with pygame-ce). I tested on an SDL_image prebuilt for Windows (built with stb-image instead), and didn't see this bad output.

I looked into how this might be solved in the libpng code, but the libpng code is extremely difficult to understand. Checking the libpng docs I see that they have a "simplified API" for reading and writing, so I spent 2 days hacking on it and have a draft of using the libpng simple API instead of the older API in SDL2_image: https://github.com/pygame-community/SDL_image/blob/a89d6d9b7069e851bdfeecb15e8cc0de6b4542c6/src/IMG_png.c#L233-L367. That branch is still WIP right now, but wanted to float the idea of potentially moving over to that strategy for libpng. It seems a lot simpler than the other libpng code or even the stb-image code. (And it fixes this issue too)

pygame-ce issue: https://github.com/pygame-community/pygame-ce/issues/3036

**Comment by slouken** [comment]
Also, I fixed the underlying problem in IMG_png.c

**Comment by Starbuck5** [comment]
Thanks @slouken!

Gave it a run through the pygame-ce test suite and on that image, all worked as expected.

**Comment by slouken** [comment]
You're welcome!
