### ISSUE TITLE
static libraries include libSDLmain.a and libSDL.a, so breaking linking

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#47]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.12
**Reported for operating system, platform:** Mac OS X (All), All

# Comments on the original bug report:

On 2012-11-16 01:13:08 +0000,  wrote:

> When compiling with the configure and makefile on Mountain Lion, libSDLmain.a and libSDL.a get somehow included in libSDL_image.a. This seems to confuse ld, as I ge tthe following message in the final linking with the application:
> 
> ld: warning: ignoring file lib/libSDL_image.a, file was built for archive which is not the architecture being linked (x86_64): lib/libSDL_image.a
> 
> otool and lipo still recognize the library as a x86_64 blob. It's only clang that seems to be upset at it.
> 
> The same happens with libSDL_mixer.a, but I won't report this bug twice.
> 
> I don't know whether this is related to # 1429.

**Comment by sezero** [comment]
This SDL-1.2 branch issue won't be fixed.
