### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by HotspringEgg** [libsdl-org/SDL_image#472]
I‘m new to SDL3 and want to add image lib into my project
however i found that it did not generate a new lib like sdl2_image, only the sdl3.lib in the setting of example project, and i uesd the new one to replace the old one which was generated by SDL3_main
also i added the appropriate LOAD_* preprocessor define to the Visual Studio project., it doesnt work,the ide cannot find implementations for the functions IMG_Init, IMG_Quit, and IMG_Load.

**Comment by madebr** [comment]
This question is more appropriate for the SDL discourse server
https://discourse.libsdl.org/
