### ISSUE TITLE
IMG_Init and IMG_Quit always pull in all static libraries

### ISSUE THREAD

**Issue by ccawley2011** [libsdl-org/SDL_image#475]
`IMG_Init` and `IMG_Quit` initialise and deinitialise libraries based on the value of the flag parameter, however most compilers are unable to remove unused code this way. `IMG_Init` is also called within the load functions, so even if a program only requires `IMG_LoadPNG_RW`, the linker will still pull in all of the other libraries, which significantly increases the size of the final executable.

**Comment by slouken** [comment]
That's correct. That's why dynamic loading of external dependencies is the default.

**Comment by ccawley2011** [comment]
It's still an issue on platforms that don't support dynamic linking, though.

**Comment by slouken** [comment]
Then only build with support for the formats you want.
