### ISSUE TITLE
Can't change SDL3 directory path from cmake CLI

### ISSUE THREAD

**Issue by Dv-Senna** [libsdl-org/SDL_image#476]
As the title suggested, I can't change the location that SDL3_image search through to find SDL3. Is there an obvious mechanism I was too blind (or stupid) to see ? Because I can't find any. It would just have to be something like `-DSDL3_SEARCH_PATH=some/path`.

**Comment by madebr** [comment]
CMake's `find_package` search procedure is [documented here](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure)

**Comment by madebr** [comment]
Questions about the build procedure should be asked on the discourse server
See https://discourse.libsdl.org/
