### ISSUE TITLE
Plans for a next 2.x release?

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_image#480]
Hello, earlier this year I reported #460, which was fixed very quickly. Thanks!

I would like to bundle this fix into our release versions of pygame-ce, but we normally use release versions of dependencies, rather than intermediate git commits.

Therefore, I'm writing to request a new release. Thanks for maintaining this library!

**Comment by slouken** [comment]
I'll bump the priority for this, thanks for the feedback!

**Comment by slouken** [comment]
This has been released!
https://github.com/libsdl-org/SDL_image/releases/tag/release-2.8.3
