### ISSUE TITLE
Mismatch between definition and description in all saving functions in main branch 

### ISSUE THREAD

**Issue by ilyachastikov** [libsdl-org/SDL_image#481]
All saving functions (regular and IO) return **bool** type but all their descriptions say that 

> returns 0 if successful, -1 on error.

 And all IO saving funstions define parametes 'closeio' as **int** but descriptions say that

> param closeio true to close/free the SDL_IOStream before returning, false
  to leave it open.

**Comment by slouken** [comment]
Fixed, thanks!
