### ISSUE TITLE
SDL2_imageConfig.cmake.in resets SDL3_image_FOUND instead of SDL2_image_FOUND

### ISSUE THREAD

**Issue by molotok-sms** [libsdl-org/SDL_image#483]
The `SDL2_imageConfig.cmake.in` script resets the `SDL3_image_FOUND` variable instead of `SDL2_image_FOUND` if the `libavif` library is missing.
It leads to the continuation of the build without any errors at this stage and the inability to use the `SDL2_image::SDL2_image` package in the future.

Issue:
```
if(SDL2IMAGE_AVIF AND NOT SDL2IMAGE_VENDORED AND NOT TARGET avif)
    find_package(libavif 1.0 QUIET)
    if(NOT libavif_FOUND)
        find_package(libavif @LIBAVIF_MINIMUM_VERSION@ QUIET)
    endif()
    if(NOT libavif_FOUND)
        set(SDL3_image_FOUND FALSE)         # <-- the issue
        return()
    endif()
endif()
```

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL_image/commit/251cdd89247b25f57edc1a87dfcf17e9a8a4b407, thanks!
