### ISSUE TITLE
[SDL2] Use pre-built avif/libjxl libraries in autotools configuration

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_image#484]
The autotools detects libavif/libjx using pkg-config and custom build tests here:
https://github.com/libsdl-org/SDL_image/blob/251cdd89247b25f57edc1a87dfcf17e9a8a4b407/configure.ac#L310-L320

Is it possible to re-use the pre-built win32 binaries in [VisualC/external](https://github.com/libsdl-org/SDL_image/tree/main/VisualC/external)?

Configuring with `LIBAVIF_CFLAGS=/path/to/SDL2_image/VisualC/external/include LIBAVIF_LDFLAGS=` does still fail the libavif tests.

@sezero

**Comment by slouken** [comment]
FYI, this is a blocker for an SDL_image release, so we should resolve this.

**Comment by madebr** [comment]
Creating import libraries, and configuring with  'LIBAVIF_CFLAGS=-I/home/maarten/projects/SDL_image/VisualC/external/include' 'LIBAVIF_LDFLAGS=-L/home/maarten/projects/SDL_image/VisualC/external/optional/x86' also does not work

[avif-implib.tar.gz](https://github.com/user-attachments/files/18045073/avif-implib.tar.gz)

I created the implibs using:
```
x86_64-w64-mingw32-dlltool --input-def libavif-16.def --output-lib libavif.dll.a
i686-w64-mingw32-dlltool --input-def libavif-16.def --output-lib libavif.dll.a
```

**Comment by madebr** [comment]
I think I got it working with:
```
        "LDFLAGS=-L/src/SDL_image/VisualC/external/optional/x86"
        "LIBAVIF_CFLAGS=-I/src/SDL_image/VisualC/external/include"
        "LIBAVIF_LIBS=-L/src/SDL_image/VisualC/external/optional/x86"
        "LIBWEBPDEMUX_CFLAGS=-I/src/SDL_image/VisualC/external/include"
        "LIBWEBPDEMUX_LIBS=-L/src/SDL_image/VisualC/external/optional/x86"
        "LIBWEBP_CFLAGS=-I/src/SDL_image/VisualC/external/include"
        "LIBWEBP_LIBS=-L/src/SDL_image/VisualC/external/optional/x86"
```

**Comment by sezero** [comment]
> I think I got it working with:
> 
> ```
>         "LDFLAGS=-L/src/SDL_image/VisualC/external/optional/x86"
>         "LIBAVIF_CFLAGS=-I/src/SDL_image/VisualC/external/include"
>         "LIBAVIF_LIBS=-L/src/SDL_image/VisualC/external/optional/x86"
>         "LIBWEBPDEMUX_CFLAGS=-I/src/SDL_image/VisualC/external/include"
>         "LIBWEBPDEMUX_LIBS=-L/src/SDL_image/VisualC/external/optional/x86"
>         "LIBWEBP_CFLAGS=-I/src/SDL_image/VisualC/external/include"
>         "LIBWEBP_LIBS=-L/src/SDL_image/VisualC/external/optional/x86"
> ```

Yes, that should work I think

> FYI, this is a blocker for an SDL_image release, so we should resolve this.

Why is this a blocker? Are the sdl2 branch releases going to be made through CI artifacts?

**Comment by sezero** [comment]
> FYI, this is a blocker for an SDL_image release, so we should resolve this.

P.S.: The actual blocker is https://github.com/libsdl-org/SDL_image/issues/450 (tests failing against libjxl >= 0.10.0), which I _think_ we should ask libjxl guys for help

**Comment by madebr** [comment]
> Yes, that should work I think

It works! Proven by ci :)
> 
> > FYI, this is a blocker for an SDL_image release, so we should resolve this.
> 
> Why is this a blocker? Are the sdl2 branch releases going to be made through CI artifacts?

Yes, I've backported the scripts from the main branch, now using autotools.

It was a blocker because without it, the mingw binaries would be built without avif/webp/tiff support.
