### ISSUE TITLE
Certain transparent backgrounds render as blue since SDL_image 2.8.3 on Mac OS X

### ISSUE THREAD

**Issue by tobbi** [libsdl-org/SDL_image#494]
I'm sorry for this being rather vague because I'm not sure of the actual cause.
I've installed SDL_image 2.8.3 using Homebrew on my MacOS X 12.7.6 machine and I'm linking SuperTux against it. 

Certain previously transparent images now render with a blue background:

https://github.com/user-attachments/assets/2c76cf8a-f16a-4a1a-8e57-1f7809bd666a

I then disabled the homebrew formula and compiled 2.8.2 manually and the issue is gone:

https://github.com/user-attachments/assets/32876aa7-2afc-4f9c-9be7-6c1b9c91c1f3

If there's anything more you need, just tell me.

**Comment by slouken** [comment]
Do you get the issue if you build 2.8.3 manually? If not, what are the configure options being used by the homebrew formula?

**Comment by tobbi** [comment]
> Do you get the issue if you build 2.8.3 manually? If not, what are the configure options being used by the homebrew formula?

Apparently, linking against a self-built 2.8.3 worked just fine. Here are the homebrew configure flags: https://github.com/Homebrew/homebrew-core/blob/dba938d9df5b2e1fe399ef345d64cfa3df0c1f79/Formula/s/sdl2_image.rb#L43C1-L50C51

**Comment by tobbi** [comment]
The snow particles in question should be https://raw.githubusercontent.com/SuperTux/supertux/refs/heads/master/data/images/particles/snow0.png https://raw.githubusercontent.com/SuperTux/supertux/refs/heads/master/data/images/particles/snow1.png and https://raw.githubusercontent.com/SuperTux/supertux/refs/heads/master/data/images/particles/snow2.png

**Comment by slouken** [comment]
Can you reproduce it if you build with the same configure options that homebrew uses, and then run showimage on that image?

**Comment by sezero** [comment]
Reproduces on linux with `--disable-stb-image`, thus using libpng, in both release-2.8.x and SDL2 branches. Should possibly reproduce in SDL3 (main) branch too.

Commit https://github.com/libsdl-org/SDL_image/commit/0000fb07f267eb53023b9e648f6d126025708ada (which was cherry-picked to release-2.8.x too) seems to be the culprit.

**Comment by tobbi** [comment]
Can confirm that by adding the flags from the homebrew formula, the bug re-appears.

**Comment by slouken** [comment]
Fixed! Thanks for the help tracking this down.
