### ISSUE TITLE
ImageIO loader fails to load some png files from circuslinux

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#53]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [sample png (programming.png, image/png, 2013-02-14 11:08:35 +0000, 1288 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1043)

**Reported in version:** 1.2.12
**Reported for operating system, platform:** Mac OS X 10.5 (PPC), PowerPC

# Comments on the original bug report:

On 2013-02-14 11:06:58 +0000,  wrote:

> When compiled with ImageIO support, showimage fails to load some png files from circuslinux:
> 
> $ ./showimage /opt/local/share/circuslinux/data/images/title/programming.png 
> Couldn't load /opt/local/share/circuslinux/data/images/title/programming.png: Unknown bits_per_pixel u
> 
> Same file loads ok when compiled with --disable-imageio
> 
> See https://trac.macports.org/ticket/38012

On 2013-02-14 11:08:35 +0000,  wrote:

> Created attachment 1043
> sample png

On 2013-06-03 02:01:22 +0000, Sam Lantinga wrote:

> This appears to be fixed in the SDL_image 2.0 release candidate.
> 
> Thanks!

On 2016-04-29 12:42:24 +0000, Joshua Root wrote:

> I'm not so sure this is actually fixed. The test case on the MacPorts ticket shows that the 8-bit images are loaded fine but not the 2-bit colormaps. I suspect ImageIO on 10.5 just doesn't handle those (or at least does something unexpected with them). Nobody ever reported this problem with later OS versions.
> 
> Given that SDL2 doesn't work on 10.5 anyway it may be a moot point, but if you were inclined to fix it in a new 1.2.x release then the straightforward workaround would be to not use ImageIO on 10.5 or earlier. No idea if a real fix for 10.5 is even possible.
> 
> Feel free to just re-close as WONTFIX if you'd prefer.

**Comment by sezero** [comment]
ImageIO updates from 2.0 have been backported to SDL-1.2 branch for some time ago. Closing.
