### ISSUE TITLE
SDL_image fails to find jpeg lib with cygwin and mingw64

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#67]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Windows (All), All

# Comments on the original bug report:

On 2013-08-10 08:21:44 +0000, Martin Gerhardy wrote:

> The problem is that -XCClinker is unknown to gcc and thus SDL_image can't be build with jpeg support out of the box.
> 
> Talking about hg revision from 10th Aug

On 2013-08-10 08:23:46 +0000, Martin Gerhardy wrote:

> This -XCClinker flag comes from the SDL2 flags. SDL2 flags should not be needed to check for jpeg

On 2013-08-10 08:31:47 +0000, Martin Gerhardy wrote:

> btw. this -XCClinker flag is also removed for mingw64 when cross compiling from linux - see my mxe package at https://github.com/mxe/mxe/blob/master/src/sdl2.mk. The option is unknown there, too.
> 
> I've changed the component from SDL_image to SDL - because it's more of a bug of SDL itself imo.

On 2019-11-26 13:59:13 +0000, hart3778avery@gmx.com wrote:

> Yeah, I'm also wondering why is this -XCClinker flag necessary. http://webtrafficgeeks.org

**Comment by sezero** [comment]
This should be fixed in newer releases and/or in git tree
