### ISSUE TITLE
SDL_image 2.0.0 not building on Mac OS X 10.9

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL_image#79]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Mac OS X 10.8, x86

# Comments on the original bug report:

On 2014-02-21 23:55:24 +0000,  wrote:

> Environment:
> OS X Mavericks, GCC 4.2.1, Apple LLVM Version 5.0, Make 3.8.1
> 
> Commands:
> ./configure && make && make install
> 
> Error:
> Undefined symbols for architecture x86_64:
>   "_objc_msgSend", referenced from:
>       _Create_SDL_Surface_From_CGImage_Index in IMG_ImageIO.o
>   "_objc_msgSend_fixup", referenced from:
>       l_objc_msgSend_fixup_autorelease in IMG_ImageIO.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [libSDL2_image.la] Error 1
> 
> Apparently the Objective-C libraries weren't being linked, so I manually added an -lobjc flag to the LIBS variable in my Makefile. It compiled fine after that.

**Comment by sezero** [comment]
This has been fixed as of https://github.com/libsdl-org/SDL_image/commit/8225b3ad81aae88eda0fa0737c832ada468e9bdf
